// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/dlespiau/quay-exporter/pkg/models"
)

// NewChangeOrganizationDetailsParams creates a new ChangeOrganizationDetailsParams object
// with the default values initialized.
func NewChangeOrganizationDetailsParams() *ChangeOrganizationDetailsParams {
	var ()
	return &ChangeOrganizationDetailsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeOrganizationDetailsParamsWithTimeout creates a new ChangeOrganizationDetailsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeOrganizationDetailsParamsWithTimeout(timeout time.Duration) *ChangeOrganizationDetailsParams {
	var ()
	return &ChangeOrganizationDetailsParams{

		timeout: timeout,
	}
}

// NewChangeOrganizationDetailsParamsWithContext creates a new ChangeOrganizationDetailsParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeOrganizationDetailsParamsWithContext(ctx context.Context) *ChangeOrganizationDetailsParams {
	var ()
	return &ChangeOrganizationDetailsParams{

		Context: ctx,
	}
}

// NewChangeOrganizationDetailsParamsWithHTTPClient creates a new ChangeOrganizationDetailsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeOrganizationDetailsParamsWithHTTPClient(client *http.Client) *ChangeOrganizationDetailsParams {
	var ()
	return &ChangeOrganizationDetailsParams{
		HTTPClient: client,
	}
}

/*ChangeOrganizationDetailsParams contains all the parameters to send to the API endpoint
for the change organization details operation typically these are written to a http.Request
*/
type ChangeOrganizationDetailsParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.UpdateOrg
	/*Orgname
	  The name of the organization

	*/
	Orgname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change organization details params
func (o *ChangeOrganizationDetailsParams) WithTimeout(timeout time.Duration) *ChangeOrganizationDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change organization details params
func (o *ChangeOrganizationDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change organization details params
func (o *ChangeOrganizationDetailsParams) WithContext(ctx context.Context) *ChangeOrganizationDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change organization details params
func (o *ChangeOrganizationDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change organization details params
func (o *ChangeOrganizationDetailsParams) WithHTTPClient(client *http.Client) *ChangeOrganizationDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change organization details params
func (o *ChangeOrganizationDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the change organization details params
func (o *ChangeOrganizationDetailsParams) WithBody(body *models.UpdateOrg) *ChangeOrganizationDetailsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the change organization details params
func (o *ChangeOrganizationDetailsParams) SetBody(body *models.UpdateOrg) {
	o.Body = body
}

// WithOrgname adds the orgname to the change organization details params
func (o *ChangeOrganizationDetailsParams) WithOrgname(orgname string) *ChangeOrganizationDetailsParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the change organization details params
func (o *ChangeOrganizationDetailsParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeOrganizationDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
