// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrganizationApplicationsParams creates a new GetOrganizationApplicationsParams object
// with the default values initialized.
func NewGetOrganizationApplicationsParams() *GetOrganizationApplicationsParams {
	var ()
	return &GetOrganizationApplicationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationApplicationsParamsWithTimeout creates a new GetOrganizationApplicationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrganizationApplicationsParamsWithTimeout(timeout time.Duration) *GetOrganizationApplicationsParams {
	var ()
	return &GetOrganizationApplicationsParams{

		timeout: timeout,
	}
}

// NewGetOrganizationApplicationsParamsWithContext creates a new GetOrganizationApplicationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrganizationApplicationsParamsWithContext(ctx context.Context) *GetOrganizationApplicationsParams {
	var ()
	return &GetOrganizationApplicationsParams{

		Context: ctx,
	}
}

// NewGetOrganizationApplicationsParamsWithHTTPClient creates a new GetOrganizationApplicationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrganizationApplicationsParamsWithHTTPClient(client *http.Client) *GetOrganizationApplicationsParams {
	var ()
	return &GetOrganizationApplicationsParams{
		HTTPClient: client,
	}
}

/*GetOrganizationApplicationsParams contains all the parameters to send to the API endpoint
for the get organization applications operation typically these are written to a http.Request
*/
type GetOrganizationApplicationsParams struct {

	/*Orgname
	  The name of the organization

	*/
	Orgname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organization applications params
func (o *GetOrganizationApplicationsParams) WithTimeout(timeout time.Duration) *GetOrganizationApplicationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization applications params
func (o *GetOrganizationApplicationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization applications params
func (o *GetOrganizationApplicationsParams) WithContext(ctx context.Context) *GetOrganizationApplicationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization applications params
func (o *GetOrganizationApplicationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization applications params
func (o *GetOrganizationApplicationsParams) WithHTTPClient(client *http.Client) *GetOrganizationApplicationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization applications params
func (o *GetOrganizationApplicationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgname adds the orgname to the get organization applications params
func (o *GetOrganizationApplicationsParams) WithOrgname(orgname string) *GetOrganizationApplicationsParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the get organization applications params
func (o *GetOrganizationApplicationsParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationApplicationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
