// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrganizationApplicationParams creates a new GetOrganizationApplicationParams object
// with the default values initialized.
func NewGetOrganizationApplicationParams() *GetOrganizationApplicationParams {
	var ()
	return &GetOrganizationApplicationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationApplicationParamsWithTimeout creates a new GetOrganizationApplicationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrganizationApplicationParamsWithTimeout(timeout time.Duration) *GetOrganizationApplicationParams {
	var ()
	return &GetOrganizationApplicationParams{

		timeout: timeout,
	}
}

// NewGetOrganizationApplicationParamsWithContext creates a new GetOrganizationApplicationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrganizationApplicationParamsWithContext(ctx context.Context) *GetOrganizationApplicationParams {
	var ()
	return &GetOrganizationApplicationParams{

		Context: ctx,
	}
}

// NewGetOrganizationApplicationParamsWithHTTPClient creates a new GetOrganizationApplicationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrganizationApplicationParamsWithHTTPClient(client *http.Client) *GetOrganizationApplicationParams {
	var ()
	return &GetOrganizationApplicationParams{
		HTTPClient: client,
	}
}

/*GetOrganizationApplicationParams contains all the parameters to send to the API endpoint
for the get organization application operation typically these are written to a http.Request
*/
type GetOrganizationApplicationParams struct {

	/*ClientID
	  The OAuth client ID

	*/
	ClientID string
	/*Orgname
	  The name of the organization

	*/
	Orgname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organization application params
func (o *GetOrganizationApplicationParams) WithTimeout(timeout time.Duration) *GetOrganizationApplicationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization application params
func (o *GetOrganizationApplicationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization application params
func (o *GetOrganizationApplicationParams) WithContext(ctx context.Context) *GetOrganizationApplicationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization application params
func (o *GetOrganizationApplicationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization application params
func (o *GetOrganizationApplicationParams) WithHTTPClient(client *http.Client) *GetOrganizationApplicationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization application params
func (o *GetOrganizationApplicationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClientID adds the clientID to the get organization application params
func (o *GetOrganizationApplicationParams) WithClientID(clientID string) *GetOrganizationApplicationParams {
	o.SetClientID(clientID)
	return o
}

// SetClientID adds the clientId to the get organization application params
func (o *GetOrganizationApplicationParams) SetClientID(clientID string) {
	o.ClientID = clientID
}

// WithOrgname adds the orgname to the get organization application params
func (o *GetOrganizationApplicationParams) WithOrgname(orgname string) *GetOrganizationApplicationParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the get organization application params
func (o *GetOrganizationApplicationParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationApplicationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param client_id
	if err := r.SetPathParam("client_id", o.ClientID); err != nil {
		return err
	}

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
