// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrganizationMemberParams creates a new GetOrganizationMemberParams object
// with the default values initialized.
func NewGetOrganizationMemberParams() *GetOrganizationMemberParams {
	var ()
	return &GetOrganizationMemberParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationMemberParamsWithTimeout creates a new GetOrganizationMemberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrganizationMemberParamsWithTimeout(timeout time.Duration) *GetOrganizationMemberParams {
	var ()
	return &GetOrganizationMemberParams{

		timeout: timeout,
	}
}

// NewGetOrganizationMemberParamsWithContext creates a new GetOrganizationMemberParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrganizationMemberParamsWithContext(ctx context.Context) *GetOrganizationMemberParams {
	var ()
	return &GetOrganizationMemberParams{

		Context: ctx,
	}
}

// NewGetOrganizationMemberParamsWithHTTPClient creates a new GetOrganizationMemberParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrganizationMemberParamsWithHTTPClient(client *http.Client) *GetOrganizationMemberParams {
	var ()
	return &GetOrganizationMemberParams{
		HTTPClient: client,
	}
}

/*GetOrganizationMemberParams contains all the parameters to send to the API endpoint
for the get organization member operation typically these are written to a http.Request
*/
type GetOrganizationMemberParams struct {

	/*Membername
	  The username of the organization member

	*/
	Membername string
	/*Orgname
	  The name of the organization

	*/
	Orgname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organization member params
func (o *GetOrganizationMemberParams) WithTimeout(timeout time.Duration) *GetOrganizationMemberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization member params
func (o *GetOrganizationMemberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization member params
func (o *GetOrganizationMemberParams) WithContext(ctx context.Context) *GetOrganizationMemberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization member params
func (o *GetOrganizationMemberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization member params
func (o *GetOrganizationMemberParams) WithHTTPClient(client *http.Client) *GetOrganizationMemberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization member params
func (o *GetOrganizationMemberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMembername adds the membername to the get organization member params
func (o *GetOrganizationMemberParams) WithMembername(membername string) *GetOrganizationMemberParams {
	o.SetMembername(membername)
	return o
}

// SetMembername adds the membername to the get organization member params
func (o *GetOrganizationMemberParams) SetMembername(membername string) {
	o.Membername = membername
}

// WithOrgname adds the orgname to the get organization member params
func (o *GetOrganizationMemberParams) WithOrgname(orgname string) *GetOrganizationMemberParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the get organization member params
func (o *GetOrganizationMemberParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationMemberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param membername
	if err := r.SetPathParam("membername", o.Membername); err != nil {
		return err
	}

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
