// Code generated by go-swagger; DO NOT EDIT.

package prototype

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteOrganizationPrototypePermissionParams creates a new DeleteOrganizationPrototypePermissionParams object
// with the default values initialized.
func NewDeleteOrganizationPrototypePermissionParams() *DeleteOrganizationPrototypePermissionParams {
	var ()
	return &DeleteOrganizationPrototypePermissionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOrganizationPrototypePermissionParamsWithTimeout creates a new DeleteOrganizationPrototypePermissionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteOrganizationPrototypePermissionParamsWithTimeout(timeout time.Duration) *DeleteOrganizationPrototypePermissionParams {
	var ()
	return &DeleteOrganizationPrototypePermissionParams{

		timeout: timeout,
	}
}

// NewDeleteOrganizationPrototypePermissionParamsWithContext creates a new DeleteOrganizationPrototypePermissionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteOrganizationPrototypePermissionParamsWithContext(ctx context.Context) *DeleteOrganizationPrototypePermissionParams {
	var ()
	return &DeleteOrganizationPrototypePermissionParams{

		Context: ctx,
	}
}

// NewDeleteOrganizationPrototypePermissionParamsWithHTTPClient creates a new DeleteOrganizationPrototypePermissionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteOrganizationPrototypePermissionParamsWithHTTPClient(client *http.Client) *DeleteOrganizationPrototypePermissionParams {
	var ()
	return &DeleteOrganizationPrototypePermissionParams{
		HTTPClient: client,
	}
}

/*DeleteOrganizationPrototypePermissionParams contains all the parameters to send to the API endpoint
for the delete organization prototype permission operation typically these are written to a http.Request
*/
type DeleteOrganizationPrototypePermissionParams struct {

	/*Orgname
	  The name of the organization

	*/
	Orgname string
	/*Prototypeid
	  The ID of the prototype

	*/
	Prototypeid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete organization prototype permission params
func (o *DeleteOrganizationPrototypePermissionParams) WithTimeout(timeout time.Duration) *DeleteOrganizationPrototypePermissionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete organization prototype permission params
func (o *DeleteOrganizationPrototypePermissionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete organization prototype permission params
func (o *DeleteOrganizationPrototypePermissionParams) WithContext(ctx context.Context) *DeleteOrganizationPrototypePermissionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete organization prototype permission params
func (o *DeleteOrganizationPrototypePermissionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete organization prototype permission params
func (o *DeleteOrganizationPrototypePermissionParams) WithHTTPClient(client *http.Client) *DeleteOrganizationPrototypePermissionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete organization prototype permission params
func (o *DeleteOrganizationPrototypePermissionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgname adds the orgname to the delete organization prototype permission params
func (o *DeleteOrganizationPrototypePermissionParams) WithOrgname(orgname string) *DeleteOrganizationPrototypePermissionParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the delete organization prototype permission params
func (o *DeleteOrganizationPrototypePermissionParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WithPrototypeid adds the prototypeid to the delete organization prototype permission params
func (o *DeleteOrganizationPrototypePermissionParams) WithPrototypeid(prototypeid string) *DeleteOrganizationPrototypePermissionParams {
	o.SetPrototypeid(prototypeid)
	return o
}

// SetPrototypeid adds the prototypeid to the delete organization prototype permission params
func (o *DeleteOrganizationPrototypePermissionParams) SetPrototypeid(prototypeid string) {
	o.Prototypeid = prototypeid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrganizationPrototypePermissionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	// path param prototypeid
	if err := r.SetPathParam("prototypeid", o.Prototypeid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
