// Code generated by go-swagger; DO NOT EDIT.

package prototype

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrganizationPrototypePermissionsParams creates a new GetOrganizationPrototypePermissionsParams object
// with the default values initialized.
func NewGetOrganizationPrototypePermissionsParams() *GetOrganizationPrototypePermissionsParams {
	var ()
	return &GetOrganizationPrototypePermissionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationPrototypePermissionsParamsWithTimeout creates a new GetOrganizationPrototypePermissionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrganizationPrototypePermissionsParamsWithTimeout(timeout time.Duration) *GetOrganizationPrototypePermissionsParams {
	var ()
	return &GetOrganizationPrototypePermissionsParams{

		timeout: timeout,
	}
}

// NewGetOrganizationPrototypePermissionsParamsWithContext creates a new GetOrganizationPrototypePermissionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrganizationPrototypePermissionsParamsWithContext(ctx context.Context) *GetOrganizationPrototypePermissionsParams {
	var ()
	return &GetOrganizationPrototypePermissionsParams{

		Context: ctx,
	}
}

// NewGetOrganizationPrototypePermissionsParamsWithHTTPClient creates a new GetOrganizationPrototypePermissionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrganizationPrototypePermissionsParamsWithHTTPClient(client *http.Client) *GetOrganizationPrototypePermissionsParams {
	var ()
	return &GetOrganizationPrototypePermissionsParams{
		HTTPClient: client,
	}
}

/*GetOrganizationPrototypePermissionsParams contains all the parameters to send to the API endpoint
for the get organization prototype permissions operation typically these are written to a http.Request
*/
type GetOrganizationPrototypePermissionsParams struct {

	/*Orgname
	  The name of the organization

	*/
	Orgname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organization prototype permissions params
func (o *GetOrganizationPrototypePermissionsParams) WithTimeout(timeout time.Duration) *GetOrganizationPrototypePermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization prototype permissions params
func (o *GetOrganizationPrototypePermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization prototype permissions params
func (o *GetOrganizationPrototypePermissionsParams) WithContext(ctx context.Context) *GetOrganizationPrototypePermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization prototype permissions params
func (o *GetOrganizationPrototypePermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization prototype permissions params
func (o *GetOrganizationPrototypePermissionsParams) WithHTTPClient(client *http.Client) *GetOrganizationPrototypePermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization prototype permissions params
func (o *GetOrganizationPrototypePermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgname adds the orgname to the get organization prototype permissions params
func (o *GetOrganizationPrototypePermissionsParams) WithOrgname(orgname string) *GetOrganizationPrototypePermissionsParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the get organization prototype permissions params
func (o *GetOrganizationPrototypePermissionsParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationPrototypePermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
