// Code generated by go-swagger; DO NOT EDIT.

package repositorynotification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListRepoNotificationsParams creates a new ListRepoNotificationsParams object
// with the default values initialized.
func NewListRepoNotificationsParams() *ListRepoNotificationsParams {
	var ()
	return &ListRepoNotificationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListRepoNotificationsParamsWithTimeout creates a new ListRepoNotificationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListRepoNotificationsParamsWithTimeout(timeout time.Duration) *ListRepoNotificationsParams {
	var ()
	return &ListRepoNotificationsParams{

		timeout: timeout,
	}
}

// NewListRepoNotificationsParamsWithContext creates a new ListRepoNotificationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListRepoNotificationsParamsWithContext(ctx context.Context) *ListRepoNotificationsParams {
	var ()
	return &ListRepoNotificationsParams{

		Context: ctx,
	}
}

// NewListRepoNotificationsParamsWithHTTPClient creates a new ListRepoNotificationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListRepoNotificationsParamsWithHTTPClient(client *http.Client) *ListRepoNotificationsParams {
	var ()
	return &ListRepoNotificationsParams{
		HTTPClient: client,
	}
}

/*ListRepoNotificationsParams contains all the parameters to send to the API endpoint
for the list repo notifications operation typically these are written to a http.Request
*/
type ListRepoNotificationsParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list repo notifications params
func (o *ListRepoNotificationsParams) WithTimeout(timeout time.Duration) *ListRepoNotificationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list repo notifications params
func (o *ListRepoNotificationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list repo notifications params
func (o *ListRepoNotificationsParams) WithContext(ctx context.Context) *ListRepoNotificationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list repo notifications params
func (o *ListRepoNotificationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list repo notifications params
func (o *ListRepoNotificationsParams) WithHTTPClient(client *http.Client) *ListRepoNotificationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list repo notifications params
func (o *ListRepoNotificationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepository adds the repository to the list repo notifications params
func (o *ListRepoNotificationsParams) WithRepository(repository string) *ListRepoNotificationsParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the list repo notifications params
func (o *ListRepoNotificationsParams) SetRepository(repository string) {
	o.Repository = repository
}

// WriteToRequest writes these params to a swagger request
func (o *ListRepoNotificationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
