// Code generated by go-swagger; DO NOT EDIT.

package repositorynotification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewResetRepositoryNotificationFailuresParams creates a new ResetRepositoryNotificationFailuresParams object
// with the default values initialized.
func NewResetRepositoryNotificationFailuresParams() *ResetRepositoryNotificationFailuresParams {
	var ()
	return &ResetRepositoryNotificationFailuresParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewResetRepositoryNotificationFailuresParamsWithTimeout creates a new ResetRepositoryNotificationFailuresParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewResetRepositoryNotificationFailuresParamsWithTimeout(timeout time.Duration) *ResetRepositoryNotificationFailuresParams {
	var ()
	return &ResetRepositoryNotificationFailuresParams{

		timeout: timeout,
	}
}

// NewResetRepositoryNotificationFailuresParamsWithContext creates a new ResetRepositoryNotificationFailuresParams object
// with the default values initialized, and the ability to set a context for a request
func NewResetRepositoryNotificationFailuresParamsWithContext(ctx context.Context) *ResetRepositoryNotificationFailuresParams {
	var ()
	return &ResetRepositoryNotificationFailuresParams{

		Context: ctx,
	}
}

// NewResetRepositoryNotificationFailuresParamsWithHTTPClient creates a new ResetRepositoryNotificationFailuresParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewResetRepositoryNotificationFailuresParamsWithHTTPClient(client *http.Client) *ResetRepositoryNotificationFailuresParams {
	var ()
	return &ResetRepositoryNotificationFailuresParams{
		HTTPClient: client,
	}
}

/*ResetRepositoryNotificationFailuresParams contains all the parameters to send to the API endpoint
for the reset repository notification failures operation typically these are written to a http.Request
*/
type ResetRepositoryNotificationFailuresParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*UUID
	  The UUID of the notification

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the reset repository notification failures params
func (o *ResetRepositoryNotificationFailuresParams) WithTimeout(timeout time.Duration) *ResetRepositoryNotificationFailuresParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reset repository notification failures params
func (o *ResetRepositoryNotificationFailuresParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reset repository notification failures params
func (o *ResetRepositoryNotificationFailuresParams) WithContext(ctx context.Context) *ResetRepositoryNotificationFailuresParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reset repository notification failures params
func (o *ResetRepositoryNotificationFailuresParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reset repository notification failures params
func (o *ResetRepositoryNotificationFailuresParams) WithHTTPClient(client *http.Client) *ResetRepositoryNotificationFailuresParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reset repository notification failures params
func (o *ResetRepositoryNotificationFailuresParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepository adds the repository to the reset repository notification failures params
func (o *ResetRepositoryNotificationFailuresParams) WithRepository(repository string) *ResetRepositoryNotificationFailuresParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the reset repository notification failures params
func (o *ResetRepositoryNotificationFailuresParams) SetRepository(repository string) {
	o.Repository = repository
}

// WithUUID adds the uuid to the reset repository notification failures params
func (o *ResetRepositoryNotificationFailuresParams) WithUUID(uuid string) *ResetRepositoryNotificationFailuresParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the reset repository notification failures params
func (o *ResetRepositoryNotificationFailuresParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *ResetRepositoryNotificationFailuresParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
