// Code generated by go-swagger; DO NOT EDIT.

package repositorynotification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTestRepoNotificationParams creates a new TestRepoNotificationParams object
// with the default values initialized.
func NewTestRepoNotificationParams() *TestRepoNotificationParams {
	var ()
	return &TestRepoNotificationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTestRepoNotificationParamsWithTimeout creates a new TestRepoNotificationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTestRepoNotificationParamsWithTimeout(timeout time.Duration) *TestRepoNotificationParams {
	var ()
	return &TestRepoNotificationParams{

		timeout: timeout,
	}
}

// NewTestRepoNotificationParamsWithContext creates a new TestRepoNotificationParams object
// with the default values initialized, and the ability to set a context for a request
func NewTestRepoNotificationParamsWithContext(ctx context.Context) *TestRepoNotificationParams {
	var ()
	return &TestRepoNotificationParams{

		Context: ctx,
	}
}

// NewTestRepoNotificationParamsWithHTTPClient creates a new TestRepoNotificationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTestRepoNotificationParamsWithHTTPClient(client *http.Client) *TestRepoNotificationParams {
	var ()
	return &TestRepoNotificationParams{
		HTTPClient: client,
	}
}

/*TestRepoNotificationParams contains all the parameters to send to the API endpoint
for the test repo notification operation typically these are written to a http.Request
*/
type TestRepoNotificationParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*UUID
	  The UUID of the notification

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the test repo notification params
func (o *TestRepoNotificationParams) WithTimeout(timeout time.Duration) *TestRepoNotificationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the test repo notification params
func (o *TestRepoNotificationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the test repo notification params
func (o *TestRepoNotificationParams) WithContext(ctx context.Context) *TestRepoNotificationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the test repo notification params
func (o *TestRepoNotificationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the test repo notification params
func (o *TestRepoNotificationParams) WithHTTPClient(client *http.Client) *TestRepoNotificationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the test repo notification params
func (o *TestRepoNotificationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepository adds the repository to the test repo notification params
func (o *TestRepoNotificationParams) WithRepository(repository string) *TestRepoNotificationParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the test repo notification params
func (o *TestRepoNotificationParams) SetRepository(repository string) {
	o.Repository = repository
}

// WithUUID adds the uuid to the test repo notification params
func (o *TestRepoNotificationParams) WithUUID(uuid string) *TestRepoNotificationParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the test repo notification params
func (o *TestRepoNotificationParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *TestRepoNotificationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
