// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrganizationTeamPermissionsParams creates a new GetOrganizationTeamPermissionsParams object
// with the default values initialized.
func NewGetOrganizationTeamPermissionsParams() *GetOrganizationTeamPermissionsParams {
	var ()
	return &GetOrganizationTeamPermissionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationTeamPermissionsParamsWithTimeout creates a new GetOrganizationTeamPermissionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrganizationTeamPermissionsParamsWithTimeout(timeout time.Duration) *GetOrganizationTeamPermissionsParams {
	var ()
	return &GetOrganizationTeamPermissionsParams{

		timeout: timeout,
	}
}

// NewGetOrganizationTeamPermissionsParamsWithContext creates a new GetOrganizationTeamPermissionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrganizationTeamPermissionsParamsWithContext(ctx context.Context) *GetOrganizationTeamPermissionsParams {
	var ()
	return &GetOrganizationTeamPermissionsParams{

		Context: ctx,
	}
}

// NewGetOrganizationTeamPermissionsParamsWithHTTPClient creates a new GetOrganizationTeamPermissionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrganizationTeamPermissionsParamsWithHTTPClient(client *http.Client) *GetOrganizationTeamPermissionsParams {
	var ()
	return &GetOrganizationTeamPermissionsParams{
		HTTPClient: client,
	}
}

/*GetOrganizationTeamPermissionsParams contains all the parameters to send to the API endpoint
for the get organization team permissions operation typically these are written to a http.Request
*/
type GetOrganizationTeamPermissionsParams struct {

	/*Orgname
	  The name of the organization

	*/
	Orgname string
	/*Teamname
	  The name of the team

	*/
	Teamname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organization team permissions params
func (o *GetOrganizationTeamPermissionsParams) WithTimeout(timeout time.Duration) *GetOrganizationTeamPermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization team permissions params
func (o *GetOrganizationTeamPermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization team permissions params
func (o *GetOrganizationTeamPermissionsParams) WithContext(ctx context.Context) *GetOrganizationTeamPermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization team permissions params
func (o *GetOrganizationTeamPermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization team permissions params
func (o *GetOrganizationTeamPermissionsParams) WithHTTPClient(client *http.Client) *GetOrganizationTeamPermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization team permissions params
func (o *GetOrganizationTeamPermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgname adds the orgname to the get organization team permissions params
func (o *GetOrganizationTeamPermissionsParams) WithOrgname(orgname string) *GetOrganizationTeamPermissionsParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the get organization team permissions params
func (o *GetOrganizationTeamPermissionsParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WithTeamname adds the teamname to the get organization team permissions params
func (o *GetOrganizationTeamPermissionsParams) WithTeamname(teamname string) *GetOrganizationTeamPermissionsParams {
	o.SetTeamname(teamname)
	return o
}

// SetTeamname adds the teamname to the get organization team permissions params
func (o *GetOrganizationTeamPermissionsParams) SetTeamname(teamname string) {
	o.Teamname = teamname
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationTeamPermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	// path param teamname
	if err := r.SetPathParam("teamname", o.Teamname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
