// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrganizationTeamMembersParams creates a new GetOrganizationTeamMembersParams object
// with the default values initialized.
func NewGetOrganizationTeamMembersParams() *GetOrganizationTeamMembersParams {
	var ()
	return &GetOrganizationTeamMembersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationTeamMembersParamsWithTimeout creates a new GetOrganizationTeamMembersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrganizationTeamMembersParamsWithTimeout(timeout time.Duration) *GetOrganizationTeamMembersParams {
	var ()
	return &GetOrganizationTeamMembersParams{

		timeout: timeout,
	}
}

// NewGetOrganizationTeamMembersParamsWithContext creates a new GetOrganizationTeamMembersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrganizationTeamMembersParamsWithContext(ctx context.Context) *GetOrganizationTeamMembersParams {
	var ()
	return &GetOrganizationTeamMembersParams{

		Context: ctx,
	}
}

// NewGetOrganizationTeamMembersParamsWithHTTPClient creates a new GetOrganizationTeamMembersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrganizationTeamMembersParamsWithHTTPClient(client *http.Client) *GetOrganizationTeamMembersParams {
	var ()
	return &GetOrganizationTeamMembersParams{
		HTTPClient: client,
	}
}

/*GetOrganizationTeamMembersParams contains all the parameters to send to the API endpoint
for the get organization team members operation typically these are written to a http.Request
*/
type GetOrganizationTeamMembersParams struct {

	/*IncludePending
	  Whether to include pending members

	*/
	IncludePending *bool
	/*Orgname
	  The name of the organization

	*/
	Orgname string
	/*Teamname
	  The name of the team

	*/
	Teamname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organization team members params
func (o *GetOrganizationTeamMembersParams) WithTimeout(timeout time.Duration) *GetOrganizationTeamMembersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization team members params
func (o *GetOrganizationTeamMembersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization team members params
func (o *GetOrganizationTeamMembersParams) WithContext(ctx context.Context) *GetOrganizationTeamMembersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization team members params
func (o *GetOrganizationTeamMembersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization team members params
func (o *GetOrganizationTeamMembersParams) WithHTTPClient(client *http.Client) *GetOrganizationTeamMembersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization team members params
func (o *GetOrganizationTeamMembersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIncludePending adds the includePending to the get organization team members params
func (o *GetOrganizationTeamMembersParams) WithIncludePending(includePending *bool) *GetOrganizationTeamMembersParams {
	o.SetIncludePending(includePending)
	return o
}

// SetIncludePending adds the includePending to the get organization team members params
func (o *GetOrganizationTeamMembersParams) SetIncludePending(includePending *bool) {
	o.IncludePending = includePending
}

// WithOrgname adds the orgname to the get organization team members params
func (o *GetOrganizationTeamMembersParams) WithOrgname(orgname string) *GetOrganizationTeamMembersParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the get organization team members params
func (o *GetOrganizationTeamMembersParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WithTeamname adds the teamname to the get organization team members params
func (o *GetOrganizationTeamMembersParams) WithTeamname(teamname string) *GetOrganizationTeamMembersParams {
	o.SetTeamname(teamname)
	return o
}

// SetTeamname adds the teamname to the get organization team members params
func (o *GetOrganizationTeamMembersParams) SetTeamname(teamname string) {
	o.Teamname = teamname
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationTeamMembersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IncludePending != nil {

		// query param includePending
		var qrIncludePending bool
		if o.IncludePending != nil {
			qrIncludePending = *o.IncludePending
		}
		qIncludePending := swag.FormatBool(qrIncludePending)
		if qIncludePending != "" {
			if err := r.SetQueryParam("includePending", qIncludePending); err != nil {
				return err
			}
		}

	}

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	// path param teamname
	if err := r.SetPathParam("teamname", o.Teamname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
