// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewInviteTeamMemberEmailParams creates a new InviteTeamMemberEmailParams object
// with the default values initialized.
func NewInviteTeamMemberEmailParams() *InviteTeamMemberEmailParams {
	var ()
	return &InviteTeamMemberEmailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInviteTeamMemberEmailParamsWithTimeout creates a new InviteTeamMemberEmailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInviteTeamMemberEmailParamsWithTimeout(timeout time.Duration) *InviteTeamMemberEmailParams {
	var ()
	return &InviteTeamMemberEmailParams{

		timeout: timeout,
	}
}

// NewInviteTeamMemberEmailParamsWithContext creates a new InviteTeamMemberEmailParams object
// with the default values initialized, and the ability to set a context for a request
func NewInviteTeamMemberEmailParamsWithContext(ctx context.Context) *InviteTeamMemberEmailParams {
	var ()
	return &InviteTeamMemberEmailParams{

		Context: ctx,
	}
}

// NewInviteTeamMemberEmailParamsWithHTTPClient creates a new InviteTeamMemberEmailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInviteTeamMemberEmailParamsWithHTTPClient(client *http.Client) *InviteTeamMemberEmailParams {
	var ()
	return &InviteTeamMemberEmailParams{
		HTTPClient: client,
	}
}

/*InviteTeamMemberEmailParams contains all the parameters to send to the API endpoint
for the invite team member email operation typically these are written to a http.Request
*/
type InviteTeamMemberEmailParams struct {

	/*Email*/
	Email string
	/*Orgname*/
	Orgname string
	/*Teamname*/
	Teamname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the invite team member email params
func (o *InviteTeamMemberEmailParams) WithTimeout(timeout time.Duration) *InviteTeamMemberEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the invite team member email params
func (o *InviteTeamMemberEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the invite team member email params
func (o *InviteTeamMemberEmailParams) WithContext(ctx context.Context) *InviteTeamMemberEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the invite team member email params
func (o *InviteTeamMemberEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the invite team member email params
func (o *InviteTeamMemberEmailParams) WithHTTPClient(client *http.Client) *InviteTeamMemberEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the invite team member email params
func (o *InviteTeamMemberEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the invite team member email params
func (o *InviteTeamMemberEmailParams) WithEmail(email string) *InviteTeamMemberEmailParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the invite team member email params
func (o *InviteTeamMemberEmailParams) SetEmail(email string) {
	o.Email = email
}

// WithOrgname adds the orgname to the invite team member email params
func (o *InviteTeamMemberEmailParams) WithOrgname(orgname string) *InviteTeamMemberEmailParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the invite team member email params
func (o *InviteTeamMemberEmailParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WithTeamname adds the teamname to the invite team member email params
func (o *InviteTeamMemberEmailParams) WithTeamname(teamname string) *InviteTeamMemberEmailParams {
	o.SetTeamname(teamname)
	return o
}

// SetTeamname adds the teamname to the invite team member email params
func (o *InviteTeamMemberEmailParams) SetTeamname(teamname string) {
	o.Teamname = teamname
}

// WriteToRequest writes these params to a swagger request
func (o *InviteTeamMemberEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param email
	if err := r.SetPathParam("email", o.Email); err != nil {
		return err
	}

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	// path param teamname
	if err := r.SetPathParam("teamname", o.Teamname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
