// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/dlespiau/quay-exporter/pkg/models"
)

// NewUpdateOrganizationTeamParams creates a new UpdateOrganizationTeamParams object
// with the default values initialized.
func NewUpdateOrganizationTeamParams() *UpdateOrganizationTeamParams {
	var ()
	return &UpdateOrganizationTeamParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateOrganizationTeamParamsWithTimeout creates a new UpdateOrganizationTeamParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateOrganizationTeamParamsWithTimeout(timeout time.Duration) *UpdateOrganizationTeamParams {
	var ()
	return &UpdateOrganizationTeamParams{

		timeout: timeout,
	}
}

// NewUpdateOrganizationTeamParamsWithContext creates a new UpdateOrganizationTeamParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateOrganizationTeamParamsWithContext(ctx context.Context) *UpdateOrganizationTeamParams {
	var ()
	return &UpdateOrganizationTeamParams{

		Context: ctx,
	}
}

// NewUpdateOrganizationTeamParamsWithHTTPClient creates a new UpdateOrganizationTeamParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateOrganizationTeamParamsWithHTTPClient(client *http.Client) *UpdateOrganizationTeamParams {
	var ()
	return &UpdateOrganizationTeamParams{
		HTTPClient: client,
	}
}

/*UpdateOrganizationTeamParams contains all the parameters to send to the API endpoint
for the update organization team operation typically these are written to a http.Request
*/
type UpdateOrganizationTeamParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.TeamDescription
	/*Orgname
	  The name of the organization

	*/
	Orgname string
	/*Teamname
	  The name of the team

	*/
	Teamname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update organization team params
func (o *UpdateOrganizationTeamParams) WithTimeout(timeout time.Duration) *UpdateOrganizationTeamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update organization team params
func (o *UpdateOrganizationTeamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update organization team params
func (o *UpdateOrganizationTeamParams) WithContext(ctx context.Context) *UpdateOrganizationTeamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update organization team params
func (o *UpdateOrganizationTeamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update organization team params
func (o *UpdateOrganizationTeamParams) WithHTTPClient(client *http.Client) *UpdateOrganizationTeamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update organization team params
func (o *UpdateOrganizationTeamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update organization team params
func (o *UpdateOrganizationTeamParams) WithBody(body *models.TeamDescription) *UpdateOrganizationTeamParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update organization team params
func (o *UpdateOrganizationTeamParams) SetBody(body *models.TeamDescription) {
	o.Body = body
}

// WithOrgname adds the orgname to the update organization team params
func (o *UpdateOrganizationTeamParams) WithOrgname(orgname string) *UpdateOrganizationTeamParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the update organization team params
func (o *UpdateOrganizationTeamParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WithTeamname adds the teamname to the update organization team params
func (o *UpdateOrganizationTeamParams) WithTeamname(teamname string) *UpdateOrganizationTeamParams {
	o.SetTeamname(teamname)
	return o
}

// SetTeamname adds the teamname to the update organization team params
func (o *UpdateOrganizationTeamParams) SetTeamname(teamname string) {
	o.Teamname = teamname
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateOrganizationTeamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	// path param teamname
	if err := r.SetPathParam("teamname", o.Teamname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
