// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteStarParams creates a new DeleteStarParams object
// with the default values initialized.
func NewDeleteStarParams() *DeleteStarParams {
	var ()
	return &DeleteStarParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteStarParamsWithTimeout creates a new DeleteStarParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteStarParamsWithTimeout(timeout time.Duration) *DeleteStarParams {
	var ()
	return &DeleteStarParams{

		timeout: timeout,
	}
}

// NewDeleteStarParamsWithContext creates a new DeleteStarParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteStarParamsWithContext(ctx context.Context) *DeleteStarParams {
	var ()
	return &DeleteStarParams{

		Context: ctx,
	}
}

// NewDeleteStarParamsWithHTTPClient creates a new DeleteStarParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteStarParamsWithHTTPClient(client *http.Client) *DeleteStarParams {
	var ()
	return &DeleteStarParams{
		HTTPClient: client,
	}
}

/*DeleteStarParams contains all the parameters to send to the API endpoint
for the delete star operation typically these are written to a http.Request
*/
type DeleteStarParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete star params
func (o *DeleteStarParams) WithTimeout(timeout time.Duration) *DeleteStarParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete star params
func (o *DeleteStarParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete star params
func (o *DeleteStarParams) WithContext(ctx context.Context) *DeleteStarParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete star params
func (o *DeleteStarParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete star params
func (o *DeleteStarParams) WithHTTPClient(client *http.Client) *DeleteStarParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete star params
func (o *DeleteStarParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepository adds the repository to the delete star params
func (o *DeleteStarParams) WithRepository(repository string) *DeleteStarParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the delete star params
func (o *DeleteStarParams) SetRepository(repository string) {
	o.Repository = repository
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteStarParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
