// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLoggedInUserParams creates a new GetLoggedInUserParams object
// with the default values initialized.
func NewGetLoggedInUserParams() *GetLoggedInUserParams {

	return &GetLoggedInUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLoggedInUserParamsWithTimeout creates a new GetLoggedInUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLoggedInUserParamsWithTimeout(timeout time.Duration) *GetLoggedInUserParams {

	return &GetLoggedInUserParams{

		timeout: timeout,
	}
}

// NewGetLoggedInUserParamsWithContext creates a new GetLoggedInUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLoggedInUserParamsWithContext(ctx context.Context) *GetLoggedInUserParams {

	return &GetLoggedInUserParams{

		Context: ctx,
	}
}

// NewGetLoggedInUserParamsWithHTTPClient creates a new GetLoggedInUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLoggedInUserParamsWithHTTPClient(client *http.Client) *GetLoggedInUserParams {

	return &GetLoggedInUserParams{
		HTTPClient: client,
	}
}

/*GetLoggedInUserParams contains all the parameters to send to the API endpoint
for the get logged in user operation typically these are written to a http.Request
*/
type GetLoggedInUserParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get logged in user params
func (o *GetLoggedInUserParams) WithTimeout(timeout time.Duration) *GetLoggedInUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get logged in user params
func (o *GetLoggedInUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get logged in user params
func (o *GetLoggedInUserParams) WithContext(ctx context.Context) *GetLoggedInUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get logged in user params
func (o *GetLoggedInUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get logged in user params
func (o *GetLoggedInUserParams) WithHTTPClient(client *http.Client) *GetLoggedInUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get logged in user params
func (o *GetLoggedInUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLoggedInUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
