// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUserInformationParams creates a new GetUserInformationParams object
// with the default values initialized.
func NewGetUserInformationParams() *GetUserInformationParams {
	var ()
	return &GetUserInformationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserInformationParamsWithTimeout creates a new GetUserInformationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserInformationParamsWithTimeout(timeout time.Duration) *GetUserInformationParams {
	var ()
	return &GetUserInformationParams{

		timeout: timeout,
	}
}

// NewGetUserInformationParamsWithContext creates a new GetUserInformationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUserInformationParamsWithContext(ctx context.Context) *GetUserInformationParams {
	var ()
	return &GetUserInformationParams{

		Context: ctx,
	}
}

// NewGetUserInformationParamsWithHTTPClient creates a new GetUserInformationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUserInformationParamsWithHTTPClient(client *http.Client) *GetUserInformationParams {
	var ()
	return &GetUserInformationParams{
		HTTPClient: client,
	}
}

/*GetUserInformationParams contains all the parameters to send to the API endpoint
for the get user information operation typically these are written to a http.Request
*/
type GetUserInformationParams struct {

	/*Username*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get user information params
func (o *GetUserInformationParams) WithTimeout(timeout time.Duration) *GetUserInformationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user information params
func (o *GetUserInformationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user information params
func (o *GetUserInformationParams) WithContext(ctx context.Context) *GetUserInformationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user information params
func (o *GetUserInformationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user information params
func (o *GetUserInformationParams) WithHTTPClient(client *http.Client) *GetUserInformationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user information params
func (o *GetUserInformationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUsername adds the username to the get user information params
func (o *GetUserInformationParams) WithUsername(username string) *GetUserInformationParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the get user information params
func (o *GetUserInformationParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserInformationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
