// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListStarredReposParams creates a new ListStarredReposParams object
// with the default values initialized.
func NewListStarredReposParams() *ListStarredReposParams {
	var ()
	return &ListStarredReposParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListStarredReposParamsWithTimeout creates a new ListStarredReposParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListStarredReposParamsWithTimeout(timeout time.Duration) *ListStarredReposParams {
	var ()
	return &ListStarredReposParams{

		timeout: timeout,
	}
}

// NewListStarredReposParamsWithContext creates a new ListStarredReposParams object
// with the default values initialized, and the ability to set a context for a request
func NewListStarredReposParamsWithContext(ctx context.Context) *ListStarredReposParams {
	var ()
	return &ListStarredReposParams{

		Context: ctx,
	}
}

// NewListStarredReposParamsWithHTTPClient creates a new ListStarredReposParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListStarredReposParamsWithHTTPClient(client *http.Client) *ListStarredReposParams {
	var ()
	return &ListStarredReposParams{
		HTTPClient: client,
	}
}

/*ListStarredReposParams contains all the parameters to send to the API endpoint
for the list starred repos operation typically these are written to a http.Request
*/
type ListStarredReposParams struct {

	/*NextPage
	  The page token for the next page

	*/
	NextPage *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list starred repos params
func (o *ListStarredReposParams) WithTimeout(timeout time.Duration) *ListStarredReposParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list starred repos params
func (o *ListStarredReposParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list starred repos params
func (o *ListStarredReposParams) WithContext(ctx context.Context) *ListStarredReposParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list starred repos params
func (o *ListStarredReposParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list starred repos params
func (o *ListStarredReposParams) WithHTTPClient(client *http.Client) *ListStarredReposParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list starred repos params
func (o *ListStarredReposParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNextPage adds the nextPage to the list starred repos params
func (o *ListStarredReposParams) WithNextPage(nextPage *string) *ListStarredReposParams {
	o.SetNextPage(nextPage)
	return o
}

// SetNextPage adds the nextPage to the list starred repos params
func (o *ListStarredReposParams) SetNextPage(nextPage *string) {
	o.NextPage = nextPage
}

// WriteToRequest writes these params to a swagger request
func (o *ListStarredReposParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.NextPage != nil {

		// query param next_page
		var qrNextPage string
		if o.NextPage != nil {
			qrNextPage = *o.NextPage
		}
		qNextPage := qrNextPage
		if qNextPage != "" {
			if err := r.SetQueryParam("next_page", qNextPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
