// Code generated by go-swagger; DO NOT EDIT.

package manifest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/dlespiau/quay-exporter/pkg/models"
)

// NewAddManifestLabelParams creates a new AddManifestLabelParams object
// with the default values initialized.
func NewAddManifestLabelParams() *AddManifestLabelParams {
	var ()
	return &AddManifestLabelParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddManifestLabelParamsWithTimeout creates a new AddManifestLabelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddManifestLabelParamsWithTimeout(timeout time.Duration) *AddManifestLabelParams {
	var ()
	return &AddManifestLabelParams{

		timeout: timeout,
	}
}

// NewAddManifestLabelParamsWithContext creates a new AddManifestLabelParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddManifestLabelParamsWithContext(ctx context.Context) *AddManifestLabelParams {
	var ()
	return &AddManifestLabelParams{

		Context: ctx,
	}
}

// NewAddManifestLabelParamsWithHTTPClient creates a new AddManifestLabelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddManifestLabelParamsWithHTTPClient(client *http.Client) *AddManifestLabelParams {
	var ()
	return &AddManifestLabelParams{
		HTTPClient: client,
	}
}

/*AddManifestLabelParams contains all the parameters to send to the API endpoint
for the add manifest label operation typically these are written to a http.Request
*/
type AddManifestLabelParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.AddLabel
	/*Manifestref
	  The digest of the manifest

	*/
	Manifestref string
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add manifest label params
func (o *AddManifestLabelParams) WithTimeout(timeout time.Duration) *AddManifestLabelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add manifest label params
func (o *AddManifestLabelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add manifest label params
func (o *AddManifestLabelParams) WithContext(ctx context.Context) *AddManifestLabelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add manifest label params
func (o *AddManifestLabelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add manifest label params
func (o *AddManifestLabelParams) WithHTTPClient(client *http.Client) *AddManifestLabelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add manifest label params
func (o *AddManifestLabelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add manifest label params
func (o *AddManifestLabelParams) WithBody(body *models.AddLabel) *AddManifestLabelParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add manifest label params
func (o *AddManifestLabelParams) SetBody(body *models.AddLabel) {
	o.Body = body
}

// WithManifestref adds the manifestref to the add manifest label params
func (o *AddManifestLabelParams) WithManifestref(manifestref string) *AddManifestLabelParams {
	o.SetManifestref(manifestref)
	return o
}

// SetManifestref adds the manifestref to the add manifest label params
func (o *AddManifestLabelParams) SetManifestref(manifestref string) {
	o.Manifestref = manifestref
}

// WithRepository adds the repository to the add manifest label params
func (o *AddManifestLabelParams) WithRepository(repository string) *AddManifestLabelParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the add manifest label params
func (o *AddManifestLabelParams) SetRepository(repository string) {
	o.Repository = repository
}

// WriteToRequest writes these params to a swagger request
func (o *AddManifestLabelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param manifestref
	if err := r.SetPathParam("manifestref", o.Manifestref); err != nil {
		return err
	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
