// Code generated by go-swagger; DO NOT EDIT.

package manifest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetManifestLabelParams creates a new GetManifestLabelParams object
// with the default values initialized.
func NewGetManifestLabelParams() *GetManifestLabelParams {
	var ()
	return &GetManifestLabelParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetManifestLabelParamsWithTimeout creates a new GetManifestLabelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetManifestLabelParamsWithTimeout(timeout time.Duration) *GetManifestLabelParams {
	var ()
	return &GetManifestLabelParams{

		timeout: timeout,
	}
}

// NewGetManifestLabelParamsWithContext creates a new GetManifestLabelParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetManifestLabelParamsWithContext(ctx context.Context) *GetManifestLabelParams {
	var ()
	return &GetManifestLabelParams{

		Context: ctx,
	}
}

// NewGetManifestLabelParamsWithHTTPClient creates a new GetManifestLabelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetManifestLabelParamsWithHTTPClient(client *http.Client) *GetManifestLabelParams {
	var ()
	return &GetManifestLabelParams{
		HTTPClient: client,
	}
}

/*GetManifestLabelParams contains all the parameters to send to the API endpoint
for the get manifest label operation typically these are written to a http.Request
*/
type GetManifestLabelParams struct {

	/*Labelid
	  The ID of the label

	*/
	Labelid string
	/*Manifestref
	  The digest of the manifest

	*/
	Manifestref string
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get manifest label params
func (o *GetManifestLabelParams) WithTimeout(timeout time.Duration) *GetManifestLabelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get manifest label params
func (o *GetManifestLabelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get manifest label params
func (o *GetManifestLabelParams) WithContext(ctx context.Context) *GetManifestLabelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get manifest label params
func (o *GetManifestLabelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get manifest label params
func (o *GetManifestLabelParams) WithHTTPClient(client *http.Client) *GetManifestLabelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get manifest label params
func (o *GetManifestLabelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLabelid adds the labelid to the get manifest label params
func (o *GetManifestLabelParams) WithLabelid(labelid string) *GetManifestLabelParams {
	o.SetLabelid(labelid)
	return o
}

// SetLabelid adds the labelid to the get manifest label params
func (o *GetManifestLabelParams) SetLabelid(labelid string) {
	o.Labelid = labelid
}

// WithManifestref adds the manifestref to the get manifest label params
func (o *GetManifestLabelParams) WithManifestref(manifestref string) *GetManifestLabelParams {
	o.SetManifestref(manifestref)
	return o
}

// SetManifestref adds the manifestref to the get manifest label params
func (o *GetManifestLabelParams) SetManifestref(manifestref string) {
	o.Manifestref = manifestref
}

// WithRepository adds the repository to the get manifest label params
func (o *GetManifestLabelParams) WithRepository(repository string) *GetManifestLabelParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the get manifest label params
func (o *GetManifestLabelParams) SetRepository(repository string) {
	o.Repository = repository
}

// WriteToRequest writes these params to a swagger request
func (o *GetManifestLabelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param labelid
	if err := r.SetPathParam("labelid", o.Labelid); err != nil {
		return err
	}

	// path param manifestref
	if err := r.SetPathParam("manifestref", o.Manifestref); err != nil {
		return err
	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
