// Code generated by go-swagger; DO NOT EDIT.

package manifest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new manifest API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for manifest API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
AddManifestLabel Adds a new label into the tag manifest.
*/
func (a *Client) AddManifestLabel(params *AddManifestLabelParams, authInfo runtime.ClientAuthInfoWriter) (*AddManifestLabelCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddManifestLabelParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "addManifestLabel",
		Method:             "POST",
		PathPattern:        "/api/v1/repository/{repository}/manifest/{manifestref}/labels",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AddManifestLabelReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*AddManifestLabelCreated), nil

}

/*
DeleteManifestLabel Deletes an existing label from a manifest.
*/
func (a *Client) DeleteManifestLabel(params *DeleteManifestLabelParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteManifestLabelNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteManifestLabelParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteManifestLabel",
		Method:             "DELETE",
		PathPattern:        "/api/v1/repository/{repository}/manifest/{manifestref}/labels/{labelid}",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteManifestLabelReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteManifestLabelNoContent), nil

}

/*
GetManifestLabel Retrieves the label with the specific ID under the manifest.
*/
func (a *Client) GetManifestLabel(params *GetManifestLabelParams, authInfo runtime.ClientAuthInfoWriter) (*GetManifestLabelOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetManifestLabelParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getManifestLabel",
		Method:             "GET",
		PathPattern:        "/api/v1/repository/{repository}/manifest/{manifestref}/labels/{labelid}",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetManifestLabelReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetManifestLabelOK), nil

}

/*
ListManifestLabels list manifest labels API
*/
func (a *Client) ListManifestLabels(params *ListManifestLabelsParams, authInfo runtime.ClientAuthInfoWriter) (*ListManifestLabelsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListManifestLabelsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listManifestLabels",
		Method:             "GET",
		PathPattern:        "/api/v1/repository/{repository}/manifest/{manifestref}/labels",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListManifestLabelsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListManifestLabelsOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
