// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteFullTagParams creates a new DeleteFullTagParams object
// with the default values initialized.
func NewDeleteFullTagParams() *DeleteFullTagParams {
	var ()
	return &DeleteFullTagParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFullTagParamsWithTimeout creates a new DeleteFullTagParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFullTagParamsWithTimeout(timeout time.Duration) *DeleteFullTagParams {
	var ()
	return &DeleteFullTagParams{

		timeout: timeout,
	}
}

// NewDeleteFullTagParamsWithContext creates a new DeleteFullTagParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteFullTagParamsWithContext(ctx context.Context) *DeleteFullTagParams {
	var ()
	return &DeleteFullTagParams{

		Context: ctx,
	}
}

// NewDeleteFullTagParamsWithHTTPClient creates a new DeleteFullTagParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteFullTagParamsWithHTTPClient(client *http.Client) *DeleteFullTagParams {
	var ()
	return &DeleteFullTagParams{
		HTTPClient: client,
	}
}

/*DeleteFullTagParams contains all the parameters to send to the API endpoint
for the delete full tag operation typically these are written to a http.Request
*/
type DeleteFullTagParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*Tag
	  The name of the tag

	*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete full tag params
func (o *DeleteFullTagParams) WithTimeout(timeout time.Duration) *DeleteFullTagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete full tag params
func (o *DeleteFullTagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete full tag params
func (o *DeleteFullTagParams) WithContext(ctx context.Context) *DeleteFullTagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete full tag params
func (o *DeleteFullTagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete full tag params
func (o *DeleteFullTagParams) WithHTTPClient(client *http.Client) *DeleteFullTagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete full tag params
func (o *DeleteFullTagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepository adds the repository to the delete full tag params
func (o *DeleteFullTagParams) WithRepository(repository string) *DeleteFullTagParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the delete full tag params
func (o *DeleteFullTagParams) SetRepository(repository string) {
	o.Repository = repository
}

// WithTag adds the tag to the delete full tag params
func (o *DeleteFullTagParams) WithTag(tag string) *DeleteFullTagParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the delete full tag params
func (o *DeleteFullTagParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFullTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
