// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/dlespiau/quay-exporter/pkg/models"
)

// NewRestoreTagParams creates a new RestoreTagParams object
// with the default values initialized.
func NewRestoreTagParams() *RestoreTagParams {
	var ()
	return &RestoreTagParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRestoreTagParamsWithTimeout creates a new RestoreTagParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRestoreTagParamsWithTimeout(timeout time.Duration) *RestoreTagParams {
	var ()
	return &RestoreTagParams{

		timeout: timeout,
	}
}

// NewRestoreTagParamsWithContext creates a new RestoreTagParams object
// with the default values initialized, and the ability to set a context for a request
func NewRestoreTagParamsWithContext(ctx context.Context) *RestoreTagParams {
	var ()
	return &RestoreTagParams{

		Context: ctx,
	}
}

// NewRestoreTagParamsWithHTTPClient creates a new RestoreTagParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRestoreTagParamsWithHTTPClient(client *http.Client) *RestoreTagParams {
	var ()
	return &RestoreTagParams{
		HTTPClient: client,
	}
}

/*RestoreTagParams contains all the parameters to send to the API endpoint
for the restore tag operation typically these are written to a http.Request
*/
type RestoreTagParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.RestoreTag
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*Tag
	  The name of the tag

	*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the restore tag params
func (o *RestoreTagParams) WithTimeout(timeout time.Duration) *RestoreTagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the restore tag params
func (o *RestoreTagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the restore tag params
func (o *RestoreTagParams) WithContext(ctx context.Context) *RestoreTagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the restore tag params
func (o *RestoreTagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the restore tag params
func (o *RestoreTagParams) WithHTTPClient(client *http.Client) *RestoreTagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the restore tag params
func (o *RestoreTagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the restore tag params
func (o *RestoreTagParams) WithBody(body *models.RestoreTag) *RestoreTagParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the restore tag params
func (o *RestoreTagParams) SetBody(body *models.RestoreTag) {
	o.Body = body
}

// WithRepository adds the repository to the restore tag params
func (o *RestoreTagParams) WithRepository(repository string) *RestoreTagParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the restore tag params
func (o *RestoreTagParams) SetRepository(repository string) {
	o.Repository = repository
}

// WithTag adds the tag to the restore tag params
func (o *RestoreTagParams) WithTag(tag string) *RestoreTagParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the restore tag params
func (o *RestoreTagParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *RestoreTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
