// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListOrgInvoicesParams creates a new ListOrgInvoicesParams object
// with the default values initialized.
func NewListOrgInvoicesParams() *ListOrgInvoicesParams {
	var ()
	return &ListOrgInvoicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListOrgInvoicesParamsWithTimeout creates a new ListOrgInvoicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListOrgInvoicesParamsWithTimeout(timeout time.Duration) *ListOrgInvoicesParams {
	var ()
	return &ListOrgInvoicesParams{

		timeout: timeout,
	}
}

// NewListOrgInvoicesParamsWithContext creates a new ListOrgInvoicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListOrgInvoicesParamsWithContext(ctx context.Context) *ListOrgInvoicesParams {
	var ()
	return &ListOrgInvoicesParams{

		Context: ctx,
	}
}

// NewListOrgInvoicesParamsWithHTTPClient creates a new ListOrgInvoicesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListOrgInvoicesParamsWithHTTPClient(client *http.Client) *ListOrgInvoicesParams {
	var ()
	return &ListOrgInvoicesParams{
		HTTPClient: client,
	}
}

/*ListOrgInvoicesParams contains all the parameters to send to the API endpoint
for the list org invoices operation typically these are written to a http.Request
*/
type ListOrgInvoicesParams struct {

	/*Orgname
	  The name of the organization

	*/
	Orgname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list org invoices params
func (o *ListOrgInvoicesParams) WithTimeout(timeout time.Duration) *ListOrgInvoicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list org invoices params
func (o *ListOrgInvoicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list org invoices params
func (o *ListOrgInvoicesParams) WithContext(ctx context.Context) *ListOrgInvoicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list org invoices params
func (o *ListOrgInvoicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list org invoices params
func (o *ListOrgInvoicesParams) WithHTTPClient(client *http.Client) *ListOrgInvoicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list org invoices params
func (o *ListOrgInvoicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgname adds the orgname to the list org invoices params
func (o *ListOrgInvoicesParams) WithOrgname(orgname string) *ListOrgInvoicesParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the list org invoices params
func (o *ListOrgInvoicesParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WriteToRequest writes these params to a swagger request
func (o *ListOrgInvoicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
