// Code generated by go-swagger; DO NOT EDIT.

package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteUserPermissionsParams creates a new DeleteUserPermissionsParams object
// with the default values initialized.
func NewDeleteUserPermissionsParams() *DeleteUserPermissionsParams {
	var ()
	return &DeleteUserPermissionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUserPermissionsParamsWithTimeout creates a new DeleteUserPermissionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteUserPermissionsParamsWithTimeout(timeout time.Duration) *DeleteUserPermissionsParams {
	var ()
	return &DeleteUserPermissionsParams{

		timeout: timeout,
	}
}

// NewDeleteUserPermissionsParamsWithContext creates a new DeleteUserPermissionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteUserPermissionsParamsWithContext(ctx context.Context) *DeleteUserPermissionsParams {
	var ()
	return &DeleteUserPermissionsParams{

		Context: ctx,
	}
}

// NewDeleteUserPermissionsParamsWithHTTPClient creates a new DeleteUserPermissionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteUserPermissionsParamsWithHTTPClient(client *http.Client) *DeleteUserPermissionsParams {
	var ()
	return &DeleteUserPermissionsParams{
		HTTPClient: client,
	}
}

/*DeleteUserPermissionsParams contains all the parameters to send to the API endpoint
for the delete user permissions operation typically these are written to a http.Request
*/
type DeleteUserPermissionsParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*Username
	  The username of the user to which the permission applies

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete user permissions params
func (o *DeleteUserPermissionsParams) WithTimeout(timeout time.Duration) *DeleteUserPermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete user permissions params
func (o *DeleteUserPermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete user permissions params
func (o *DeleteUserPermissionsParams) WithContext(ctx context.Context) *DeleteUserPermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete user permissions params
func (o *DeleteUserPermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete user permissions params
func (o *DeleteUserPermissionsParams) WithHTTPClient(client *http.Client) *DeleteUserPermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete user permissions params
func (o *DeleteUserPermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepository adds the repository to the delete user permissions params
func (o *DeleteUserPermissionsParams) WithRepository(repository string) *DeleteUserPermissionsParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the delete user permissions params
func (o *DeleteUserPermissionsParams) SetRepository(repository string) {
	o.Repository = repository
}

// WithUsername adds the username to the delete user permissions params
func (o *DeleteUserPermissionsParams) WithUsername(username string) *DeleteUserPermissionsParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the delete user permissions params
func (o *DeleteUserPermissionsParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUserPermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
