// Code generated by go-swagger; DO NOT EDIT.

package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListRepoTeamPermissionsParams creates a new ListRepoTeamPermissionsParams object
// with the default values initialized.
func NewListRepoTeamPermissionsParams() *ListRepoTeamPermissionsParams {
	var ()
	return &ListRepoTeamPermissionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListRepoTeamPermissionsParamsWithTimeout creates a new ListRepoTeamPermissionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListRepoTeamPermissionsParamsWithTimeout(timeout time.Duration) *ListRepoTeamPermissionsParams {
	var ()
	return &ListRepoTeamPermissionsParams{

		timeout: timeout,
	}
}

// NewListRepoTeamPermissionsParamsWithContext creates a new ListRepoTeamPermissionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListRepoTeamPermissionsParamsWithContext(ctx context.Context) *ListRepoTeamPermissionsParams {
	var ()
	return &ListRepoTeamPermissionsParams{

		Context: ctx,
	}
}

// NewListRepoTeamPermissionsParamsWithHTTPClient creates a new ListRepoTeamPermissionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListRepoTeamPermissionsParamsWithHTTPClient(client *http.Client) *ListRepoTeamPermissionsParams {
	var ()
	return &ListRepoTeamPermissionsParams{
		HTTPClient: client,
	}
}

/*ListRepoTeamPermissionsParams contains all the parameters to send to the API endpoint
for the list repo team permissions operation typically these are written to a http.Request
*/
type ListRepoTeamPermissionsParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list repo team permissions params
func (o *ListRepoTeamPermissionsParams) WithTimeout(timeout time.Duration) *ListRepoTeamPermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list repo team permissions params
func (o *ListRepoTeamPermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list repo team permissions params
func (o *ListRepoTeamPermissionsParams) WithContext(ctx context.Context) *ListRepoTeamPermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list repo team permissions params
func (o *ListRepoTeamPermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list repo team permissions params
func (o *ListRepoTeamPermissionsParams) WithHTTPClient(client *http.Client) *ListRepoTeamPermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list repo team permissions params
func (o *ListRepoTeamPermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepository adds the repository to the list repo team permissions params
func (o *ListRepoTeamPermissionsParams) WithRepository(repository string) *ListRepoTeamPermissionsParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the list repo team permissions params
func (o *ListRepoTeamPermissionsParams) SetRepository(repository string) {
	o.Repository = repository
}

// WriteToRequest writes these params to a swagger request
func (o *ListRepoTeamPermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
