// Code generated by go-swagger; DO NOT EDIT.

package trigger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteBuildTriggerParams creates a new DeleteBuildTriggerParams object
// with the default values initialized.
func NewDeleteBuildTriggerParams() *DeleteBuildTriggerParams {
	var ()
	return &DeleteBuildTriggerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBuildTriggerParamsWithTimeout creates a new DeleteBuildTriggerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteBuildTriggerParamsWithTimeout(timeout time.Duration) *DeleteBuildTriggerParams {
	var ()
	return &DeleteBuildTriggerParams{

		timeout: timeout,
	}
}

// NewDeleteBuildTriggerParamsWithContext creates a new DeleteBuildTriggerParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteBuildTriggerParamsWithContext(ctx context.Context) *DeleteBuildTriggerParams {
	var ()
	return &DeleteBuildTriggerParams{

		Context: ctx,
	}
}

// NewDeleteBuildTriggerParamsWithHTTPClient creates a new DeleteBuildTriggerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteBuildTriggerParamsWithHTTPClient(client *http.Client) *DeleteBuildTriggerParams {
	var ()
	return &DeleteBuildTriggerParams{
		HTTPClient: client,
	}
}

/*DeleteBuildTriggerParams contains all the parameters to send to the API endpoint
for the delete build trigger operation typically these are written to a http.Request
*/
type DeleteBuildTriggerParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*TriggerUUID
	  The UUID of the build trigger

	*/
	TriggerUUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete build trigger params
func (o *DeleteBuildTriggerParams) WithTimeout(timeout time.Duration) *DeleteBuildTriggerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete build trigger params
func (o *DeleteBuildTriggerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete build trigger params
func (o *DeleteBuildTriggerParams) WithContext(ctx context.Context) *DeleteBuildTriggerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete build trigger params
func (o *DeleteBuildTriggerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete build trigger params
func (o *DeleteBuildTriggerParams) WithHTTPClient(client *http.Client) *DeleteBuildTriggerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete build trigger params
func (o *DeleteBuildTriggerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepository adds the repository to the delete build trigger params
func (o *DeleteBuildTriggerParams) WithRepository(repository string) *DeleteBuildTriggerParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the delete build trigger params
func (o *DeleteBuildTriggerParams) SetRepository(repository string) {
	o.Repository = repository
}

// WithTriggerUUID adds the triggerUUID to the delete build trigger params
func (o *DeleteBuildTriggerParams) WithTriggerUUID(triggerUUID string) *DeleteBuildTriggerParams {
	o.SetTriggerUUID(triggerUUID)
	return o
}

// SetTriggerUUID adds the triggerUuid to the delete build trigger params
func (o *DeleteBuildTriggerParams) SetTriggerUUID(triggerUUID string) {
	o.TriggerUUID = triggerUUID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBuildTriggerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	// path param trigger_uuid
	if err := r.SetPathParam("trigger_uuid", o.TriggerUUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
