// Code generated by go-swagger; DO NOT EDIT.

package trigger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/dlespiau/quay-exporter/pkg/models"
)

// NewManuallyStartBuildTriggerParams creates a new ManuallyStartBuildTriggerParams object
// with the default values initialized.
func NewManuallyStartBuildTriggerParams() *ManuallyStartBuildTriggerParams {
	var ()
	return &ManuallyStartBuildTriggerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewManuallyStartBuildTriggerParamsWithTimeout creates a new ManuallyStartBuildTriggerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewManuallyStartBuildTriggerParamsWithTimeout(timeout time.Duration) *ManuallyStartBuildTriggerParams {
	var ()
	return &ManuallyStartBuildTriggerParams{

		timeout: timeout,
	}
}

// NewManuallyStartBuildTriggerParamsWithContext creates a new ManuallyStartBuildTriggerParams object
// with the default values initialized, and the ability to set a context for a request
func NewManuallyStartBuildTriggerParamsWithContext(ctx context.Context) *ManuallyStartBuildTriggerParams {
	var ()
	return &ManuallyStartBuildTriggerParams{

		Context: ctx,
	}
}

// NewManuallyStartBuildTriggerParamsWithHTTPClient creates a new ManuallyStartBuildTriggerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewManuallyStartBuildTriggerParamsWithHTTPClient(client *http.Client) *ManuallyStartBuildTriggerParams {
	var ()
	return &ManuallyStartBuildTriggerParams{
		HTTPClient: client,
	}
}

/*ManuallyStartBuildTriggerParams contains all the parameters to send to the API endpoint
for the manually start build trigger operation typically these are written to a http.Request
*/
type ManuallyStartBuildTriggerParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.RunParameters
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*TriggerUUID
	  The UUID of the build trigger

	*/
	TriggerUUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the manually start build trigger params
func (o *ManuallyStartBuildTriggerParams) WithTimeout(timeout time.Duration) *ManuallyStartBuildTriggerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the manually start build trigger params
func (o *ManuallyStartBuildTriggerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the manually start build trigger params
func (o *ManuallyStartBuildTriggerParams) WithContext(ctx context.Context) *ManuallyStartBuildTriggerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the manually start build trigger params
func (o *ManuallyStartBuildTriggerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the manually start build trigger params
func (o *ManuallyStartBuildTriggerParams) WithHTTPClient(client *http.Client) *ManuallyStartBuildTriggerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the manually start build trigger params
func (o *ManuallyStartBuildTriggerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the manually start build trigger params
func (o *ManuallyStartBuildTriggerParams) WithBody(body *models.RunParameters) *ManuallyStartBuildTriggerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the manually start build trigger params
func (o *ManuallyStartBuildTriggerParams) SetBody(body *models.RunParameters) {
	o.Body = body
}

// WithRepository adds the repository to the manually start build trigger params
func (o *ManuallyStartBuildTriggerParams) WithRepository(repository string) *ManuallyStartBuildTriggerParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the manually start build trigger params
func (o *ManuallyStartBuildTriggerParams) SetRepository(repository string) {
	o.Repository = repository
}

// WithTriggerUUID adds the triggerUUID to the manually start build trigger params
func (o *ManuallyStartBuildTriggerParams) WithTriggerUUID(triggerUUID string) *ManuallyStartBuildTriggerParams {
	o.SetTriggerUUID(triggerUUID)
	return o
}

// SetTriggerUUID adds the triggerUuid to the manually start build trigger params
func (o *ManuallyStartBuildTriggerParams) SetTriggerUUID(triggerUUID string) {
	o.TriggerUUID = triggerUUID
}

// WriteToRequest writes these params to a swagger request
func (o *ManuallyStartBuildTriggerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	// path param trigger_uuid
	if err := r.SetPathParam("trigger_uuid", o.TriggerUUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
