// Code generated by go-swagger; DO NOT EDIT.

package globalmessages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/dlespiau/quay-exporter/pkg/models"
)

// NewCreateGlobalMessageParams creates a new CreateGlobalMessageParams object
// with the default values initialized.
func NewCreateGlobalMessageParams() *CreateGlobalMessageParams {
	var ()
	return &CreateGlobalMessageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateGlobalMessageParamsWithTimeout creates a new CreateGlobalMessageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateGlobalMessageParamsWithTimeout(timeout time.Duration) *CreateGlobalMessageParams {
	var ()
	return &CreateGlobalMessageParams{

		timeout: timeout,
	}
}

// NewCreateGlobalMessageParamsWithContext creates a new CreateGlobalMessageParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateGlobalMessageParamsWithContext(ctx context.Context) *CreateGlobalMessageParams {
	var ()
	return &CreateGlobalMessageParams{

		Context: ctx,
	}
}

// NewCreateGlobalMessageParamsWithHTTPClient creates a new CreateGlobalMessageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateGlobalMessageParamsWithHTTPClient(client *http.Client) *CreateGlobalMessageParams {
	var ()
	return &CreateGlobalMessageParams{
		HTTPClient: client,
	}
}

/*CreateGlobalMessageParams contains all the parameters to send to the API endpoint
for the create global message operation typically these are written to a http.Request
*/
type CreateGlobalMessageParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.CreateMessage

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create global message params
func (o *CreateGlobalMessageParams) WithTimeout(timeout time.Duration) *CreateGlobalMessageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create global message params
func (o *CreateGlobalMessageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create global message params
func (o *CreateGlobalMessageParams) WithContext(ctx context.Context) *CreateGlobalMessageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create global message params
func (o *CreateGlobalMessageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create global message params
func (o *CreateGlobalMessageParams) WithHTTPClient(client *http.Client) *CreateGlobalMessageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create global message params
func (o *CreateGlobalMessageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create global message params
func (o *CreateGlobalMessageParams) WithBody(body *models.CreateMessage) *CreateGlobalMessageParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create global message params
func (o *CreateGlobalMessageParams) SetBody(body *models.CreateMessage) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateGlobalMessageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
