// Code generated by go-swagger; DO NOT EDIT.

package globalmessages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/dlespiau/quay-exporter/pkg/models"
)

// CreateGlobalMessageReader is a Reader for the CreateGlobalMessage structure.
type CreateGlobalMessageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateGlobalMessageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateGlobalMessageCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateGlobalMessageBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewCreateGlobalMessageUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewCreateGlobalMessageForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewCreateGlobalMessageNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateGlobalMessageCreated creates a CreateGlobalMessageCreated with default headers values
func NewCreateGlobalMessageCreated() *CreateGlobalMessageCreated {
	return &CreateGlobalMessageCreated{}
}

/*CreateGlobalMessageCreated handles this case with default header values.

Successful creation
*/
type CreateGlobalMessageCreated struct {
}

func (o *CreateGlobalMessageCreated) Error() string {
	return fmt.Sprintf("[POST /api/v1/messages][%d] createGlobalMessageCreated ", 201)
}

func (o *CreateGlobalMessageCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateGlobalMessageBadRequest creates a CreateGlobalMessageBadRequest with default headers values
func NewCreateGlobalMessageBadRequest() *CreateGlobalMessageBadRequest {
	return &CreateGlobalMessageBadRequest{}
}

/*CreateGlobalMessageBadRequest handles this case with default header values.

Bad Request
*/
type CreateGlobalMessageBadRequest struct {
	Payload *models.APIError
}

func (o *CreateGlobalMessageBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v1/messages][%d] createGlobalMessageBadRequest  %+v", 400, o.Payload)
}

func (o *CreateGlobalMessageBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateGlobalMessageUnauthorized creates a CreateGlobalMessageUnauthorized with default headers values
func NewCreateGlobalMessageUnauthorized() *CreateGlobalMessageUnauthorized {
	return &CreateGlobalMessageUnauthorized{}
}

/*CreateGlobalMessageUnauthorized handles this case with default header values.

Session required
*/
type CreateGlobalMessageUnauthorized struct {
	Payload *models.APIError
}

func (o *CreateGlobalMessageUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1/messages][%d] createGlobalMessageUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateGlobalMessageUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateGlobalMessageForbidden creates a CreateGlobalMessageForbidden with default headers values
func NewCreateGlobalMessageForbidden() *CreateGlobalMessageForbidden {
	return &CreateGlobalMessageForbidden{}
}

/*CreateGlobalMessageForbidden handles this case with default header values.

Unauthorized access
*/
type CreateGlobalMessageForbidden struct {
	Payload *models.APIError
}

func (o *CreateGlobalMessageForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1/messages][%d] createGlobalMessageForbidden  %+v", 403, o.Payload)
}

func (o *CreateGlobalMessageForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateGlobalMessageNotFound creates a CreateGlobalMessageNotFound with default headers values
func NewCreateGlobalMessageNotFound() *CreateGlobalMessageNotFound {
	return &CreateGlobalMessageNotFound{}
}

/*CreateGlobalMessageNotFound handles this case with default header values.

Not found
*/
type CreateGlobalMessageNotFound struct {
	Payload *models.APIError
}

func (o *CreateGlobalMessageNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1/messages][%d] createGlobalMessageNotFound  %+v", 404, o.Payload)
}

func (o *CreateGlobalMessageNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
