// Code generated by go-swagger; DO NOT EDIT.

package globalmessages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new globalmessages API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for globalmessages API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CreateGlobalMessage Create a message
*/
func (a *Client) CreateGlobalMessage(params *CreateGlobalMessageParams, authInfo runtime.ClientAuthInfoWriter) (*CreateGlobalMessageCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateGlobalMessageParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createGlobalMessage",
		Method:             "POST",
		PathPattern:        "/api/v1/messages",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateGlobalMessageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CreateGlobalMessageCreated), nil

}

/*
GetGlobalMessages Return a super users messages
*/
func (a *Client) GetGlobalMessages(params *GetGlobalMessagesParams) (*GetGlobalMessagesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetGlobalMessagesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getGlobalMessages",
		Method:             "GET",
		PathPattern:        "/api/v1/messages",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetGlobalMessagesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetGlobalMessagesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
