// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListRepositoryImagesParams creates a new ListRepositoryImagesParams object
// with the default values initialized.
func NewListRepositoryImagesParams() *ListRepositoryImagesParams {
	var ()
	return &ListRepositoryImagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListRepositoryImagesParamsWithTimeout creates a new ListRepositoryImagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListRepositoryImagesParamsWithTimeout(timeout time.Duration) *ListRepositoryImagesParams {
	var ()
	return &ListRepositoryImagesParams{

		timeout: timeout,
	}
}

// NewListRepositoryImagesParamsWithContext creates a new ListRepositoryImagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListRepositoryImagesParamsWithContext(ctx context.Context) *ListRepositoryImagesParams {
	var ()
	return &ListRepositoryImagesParams{

		Context: ctx,
	}
}

// NewListRepositoryImagesParamsWithHTTPClient creates a new ListRepositoryImagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListRepositoryImagesParamsWithHTTPClient(client *http.Client) *ListRepositoryImagesParams {
	var ()
	return &ListRepositoryImagesParams{
		HTTPClient: client,
	}
}

/*ListRepositoryImagesParams contains all the parameters to send to the API endpoint
for the list repository images operation typically these are written to a http.Request
*/
type ListRepositoryImagesParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list repository images params
func (o *ListRepositoryImagesParams) WithTimeout(timeout time.Duration) *ListRepositoryImagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list repository images params
func (o *ListRepositoryImagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list repository images params
func (o *ListRepositoryImagesParams) WithContext(ctx context.Context) *ListRepositoryImagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list repository images params
func (o *ListRepositoryImagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list repository images params
func (o *ListRepositoryImagesParams) WithHTTPClient(client *http.Client) *ListRepositoryImagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list repository images params
func (o *ListRepositoryImagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepository adds the repository to the list repository images params
func (o *ListRepositoryImagesParams) WithRepository(repository string) *ListRepositoryImagesParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the list repository images params
func (o *ListRepositoryImagesParams) SetRepository(repository string) {
	o.Repository = repository
}

// WriteToRequest writes these params to a swagger request
func (o *ListRepositoryImagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
