// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ImageSecurityData image security data
// swagger:model imageSecurityData
type ImageSecurityData struct {

	// layer
	Layer *ImageSecurityDataLayer `json:"Layer,omitempty"`
}

// Validate validates this image security data
func (m *ImageSecurityData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLayer(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImageSecurityData) validateLayer(formats strfmt.Registry) error {

	if swag.IsZero(m.Layer) { // not required
		return nil
	}

	if m.Layer != nil {

		if err := m.Layer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Layer")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImageSecurityData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageSecurityData) UnmarshalBinary(b []byte) error {
	var res ImageSecurityData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
