// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ImageSecurityDataLayerFeaturesItemsVulnerabilitiesItemsMetadataNVD image security data layer features items vulnerabilities items metadata n v d
// swagger:model imageSecurityDataLayerFeaturesItemsVulnerabilitiesItemsMetadataNVD
type ImageSecurityDataLayerFeaturesItemsVulnerabilitiesItemsMetadataNVD struct {

	// c v s sv2
	CVSSv2 *ImageSecurityDataLayerFeaturesItemsVulnerabilitiesItemsMetadataNVDCVSSv2 `json:"CVSSv2,omitempty"`
}

// Validate validates this image security data layer features items vulnerabilities items metadata n v d
func (m *ImageSecurityDataLayerFeaturesItemsVulnerabilitiesItemsMetadataNVD) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCVSSv2(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ImageSecurityDataLayerFeaturesItemsVulnerabilitiesItemsMetadataNVD) validateCVSSv2(formats strfmt.Registry) error {

	if swag.IsZero(m.CVSSv2) { // not required
		return nil
	}

	if m.CVSSv2 != nil {

		if err := m.CVSSv2.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("CVSSv2")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ImageSecurityDataLayerFeaturesItemsVulnerabilitiesItemsMetadataNVD) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageSecurityDataLayerFeaturesItemsVulnerabilitiesItemsMetadataNVD) UnmarshalBinary(b []byte) error {
	var res ImageSecurityDataLayerFeaturesItemsVulnerabilitiesItemsMetadataNVD
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
