// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ImageSecurityDataLayer image security data layer
// swagger:model imageSecurityDataLayer
type ImageSecurityDataLayer struct {

	// features
	Features ImageSecurityDataLayerFeatures `json:"Features"`

	// indexed by version
	IndexedByVersion float64 `json:"IndexedByVersion,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// namespace name
	NamespaceName string `json:"NamespaceName,omitempty"`

	// parent name
	ParentName string `json:"ParentName,omitempty"`
}

// Validate validates this image security data layer
func (m *ImageSecurityDataLayer) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ImageSecurityDataLayer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageSecurityDataLayer) UnmarshalBinary(b []byte) error {
	var res ImageSecurityDataLayer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
