// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ImageSecurityDataLayerFeaturesItems image security data layer features items
// swagger:model imageSecurityDataLayerFeaturesItems
type ImageSecurityDataLayerFeaturesItems struct {

	// added by
	AddedBy string `json:"AddedBy,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// namespace name
	NamespaceName string `json:"NamespaceName,omitempty"`

	// version
	Version string `json:"Version,omitempty"`

	// version format
	VersionFormat string `json:"VersionFormat,omitempty"`

	// vulnerabilities
	Vulnerabilities ImageSecurityDataLayerFeaturesItemsVulnerabilities `json:"Vulnerabilities"`
}

// Validate validates this image security data layer features items
func (m *ImageSecurityDataLayerFeaturesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ImageSecurityDataLayerFeaturesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ImageSecurityDataLayerFeaturesItems) UnmarshalBinary(b []byte) error {
	var res ImageSecurityDataLayerFeaturesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
