// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ListRepoTagsTagsItems list repo tags tags items
// swagger:model listRepoTagsTagsItems
type ListRepoTagsTagsItems struct {

	// docker image id
	DockerImageID string `json:"docker_image_id,omitempty"`

	// manifest digest
	ManifestDigest string `json:"manifest_digest,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// reversion
	Reversion bool `json:"reversion,omitempty"`
}

// Validate validates this list repo tags tags items
func (m *ListRepoTagsTagsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ListRepoTagsTagsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListRepoTagsTagsItems) UnmarshalBinary(b []byte) error {
	var res ListRepoTagsTagsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
