// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ListReposRepositoriesItems list repos repositories items
// swagger:model listReposRepositoriesItems
type ListReposRepositoriesItems struct {

	// description
	Description string `json:"description,omitempty"`

	// is public
	IsPublic bool `json:"is_public,omitempty"`

	// is starred
	IsStarred bool `json:"is_starred,omitempty"`

	// kind
	Kind string `json:"kind,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`
}

// Validate validates this list repos repositories items
func (m *ListReposRepositoriesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ListReposRepositoriesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListReposRepositoriesItems) UnmarshalBinary(b []byte) error {
	var res ListReposRepositoriesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
