// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewToken Description of a new token.
// swagger:model NewToken
type NewToken struct {

	// Friendly name to help identify the token
	// Required: true
	FriendlyName *string `json:"friendlyName"`
}

// Validate validates this new token
func (m *NewToken) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFriendlyName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewToken) validateFriendlyName(formats strfmt.Registry) error {

	if err := validate.Required("friendlyName", "body", m.FriendlyName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NewToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewToken) UnmarshalBinary(b []byte) error {
	var res NewToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
