// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewPrototypeDelegate Information about the user or team to which the rule grants access
// swagger:model newPrototypeDelegate
type NewPrototypeDelegate struct {

	// Whether the delegate is a user or a team
	// Required: true
	Kind *string `json:"kind"`

	// The name for the delegate team or user
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this new prototype delegate
func (m *NewPrototypeDelegate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKind(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var newPrototypeDelegateTypeKindPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["user","team"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		newPrototypeDelegateTypeKindPropEnum = append(newPrototypeDelegateTypeKindPropEnum, v)
	}
}

const (
	// NewPrototypeDelegateKindUser captures enum value "user"
	NewPrototypeDelegateKindUser string = "user"
	// NewPrototypeDelegateKindTeam captures enum value "team"
	NewPrototypeDelegateKindTeam string = "team"
)

// prop value enum
func (m *NewPrototypeDelegate) validateKindEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, newPrototypeDelegateTypeKindPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *NewPrototypeDelegate) validateKind(formats strfmt.Registry) error {

	if err := validate.Required("kind", "body", m.Kind); err != nil {
		return err
	}

	// value enum
	if err := m.validateKindEnum("kind", "body", *m.Kind); err != nil {
		return err
	}

	return nil
}

func (m *NewPrototypeDelegate) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NewPrototypeDelegate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewPrototypeDelegate) UnmarshalBinary(b []byte) error {
	var res NewPrototypeDelegate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
