// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateUser Fields which can be updated in a user.
// swagger:model UpdateUser
type UpdateUser struct {

	// The optional entered company for the user
	Company string `json:"company,omitempty"`

	// The user's email address
	Email string `json:"email,omitempty"`

	// The optional entered family name for the user
	FamilyName string `json:"family_name,omitempty"`

	// The optional entered given name for the user
	GivenName string `json:"given_name,omitempty"`

	// Whether the user desires to receive an invoice email.
	InvoiceEmail bool `json:"invoice_email,omitempty"`

	// Custom email address for receiving invoices
	InvoiceEmailAddress string `json:"invoice_email_address,omitempty"`

	// The user's password
	Password string `json:"password,omitempty"`

	// The number of seconds for tag expiration
	// Minimum: 0
	TagExpirationS *int64 `json:"tag_expiration_s,omitempty"`

	// The user's username
	Username string `json:"username,omitempty"`
}

// Validate validates this update user
func (m *UpdateUser) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTagExpirationS(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateUser) validateTagExpirationS(formats strfmt.Registry) error {

	if swag.IsZero(m.TagExpirationS) { // not required
		return nil
	}

	if err := validate.MinimumInt("tag_expiration_s", "body", int64(*m.TagExpirationS), 0, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateUser) UnmarshalBinary(b []byte) error {
	var res UpdateUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
