// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserPermission Description of a user permission.
// swagger:model UserPermission
type UserPermission struct {

	// Role to use for the user
	// Required: true
	Role *string `json:"role"`
}

// Validate validates this user permission
func (m *UserPermission) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRole(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var userPermissionTypeRolePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["read","write","admin"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		userPermissionTypeRolePropEnum = append(userPermissionTypeRolePropEnum, v)
	}
}

const (
	// UserPermissionRoleRead captures enum value "read"
	UserPermissionRoleRead string = "read"
	// UserPermissionRoleWrite captures enum value "write"
	UserPermissionRoleWrite string = "write"
	// UserPermissionRoleAdmin captures enum value "admin"
	UserPermissionRoleAdmin string = "admin"
)

// prop value enum
func (m *UserPermission) validateRoleEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, userPermissionTypeRolePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *UserPermission) validateRole(formats strfmt.Registry) error {

	if err := validate.Required("role", "body", m.Role); err != nil {
		return err
	}

	// value enum
	if err := m.validateRoleEnum("role", "body", *m.Role); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserPermission) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserPermission) UnmarshalBinary(b []byte) error {
	var res UserPermission
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
