// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/dlespiau/quay-exporter/pkg/models"
)

// NewChangeRepoTrustParams creates a new ChangeRepoTrustParams object
// with the default values initialized.
func NewChangeRepoTrustParams() *ChangeRepoTrustParams {
	var ()
	return &ChangeRepoTrustParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeRepoTrustParamsWithTimeout creates a new ChangeRepoTrustParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeRepoTrustParamsWithTimeout(timeout time.Duration) *ChangeRepoTrustParams {
	var ()
	return &ChangeRepoTrustParams{

		timeout: timeout,
	}
}

// NewChangeRepoTrustParamsWithContext creates a new ChangeRepoTrustParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeRepoTrustParamsWithContext(ctx context.Context) *ChangeRepoTrustParams {
	var ()
	return &ChangeRepoTrustParams{

		Context: ctx,
	}
}

// NewChangeRepoTrustParamsWithHTTPClient creates a new ChangeRepoTrustParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeRepoTrustParamsWithHTTPClient(client *http.Client) *ChangeRepoTrustParams {
	var ()
	return &ChangeRepoTrustParams{
		HTTPClient: client,
	}
}

/*ChangeRepoTrustParams contains all the parameters to send to the API endpoint
for the change repo trust operation typically these are written to a http.Request
*/
type ChangeRepoTrustParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.ChangeRepoTrust
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change repo trust params
func (o *ChangeRepoTrustParams) WithTimeout(timeout time.Duration) *ChangeRepoTrustParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change repo trust params
func (o *ChangeRepoTrustParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change repo trust params
func (o *ChangeRepoTrustParams) WithContext(ctx context.Context) *ChangeRepoTrustParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change repo trust params
func (o *ChangeRepoTrustParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change repo trust params
func (o *ChangeRepoTrustParams) WithHTTPClient(client *http.Client) *ChangeRepoTrustParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change repo trust params
func (o *ChangeRepoTrustParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the change repo trust params
func (o *ChangeRepoTrustParams) WithBody(body *models.ChangeRepoTrust) *ChangeRepoTrustParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the change repo trust params
func (o *ChangeRepoTrustParams) SetBody(body *models.ChangeRepoTrust) {
	o.Body = body
}

// WithRepository adds the repository to the change repo trust params
func (o *ChangeRepoTrustParams) WithRepository(repository string) *ChangeRepoTrustParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the change repo trust params
func (o *ChangeRepoTrustParams) SetRepository(repository string) {
	o.Repository = repository
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeRepoTrustParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
