// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/dlespiau/quay-exporter/pkg/models"
)

// NewChangeRepoVisibilityParams creates a new ChangeRepoVisibilityParams object
// with the default values initialized.
func NewChangeRepoVisibilityParams() *ChangeRepoVisibilityParams {
	var ()
	return &ChangeRepoVisibilityParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeRepoVisibilityParamsWithTimeout creates a new ChangeRepoVisibilityParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeRepoVisibilityParamsWithTimeout(timeout time.Duration) *ChangeRepoVisibilityParams {
	var ()
	return &ChangeRepoVisibilityParams{

		timeout: timeout,
	}
}

// NewChangeRepoVisibilityParamsWithContext creates a new ChangeRepoVisibilityParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeRepoVisibilityParamsWithContext(ctx context.Context) *ChangeRepoVisibilityParams {
	var ()
	return &ChangeRepoVisibilityParams{

		Context: ctx,
	}
}

// NewChangeRepoVisibilityParamsWithHTTPClient creates a new ChangeRepoVisibilityParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeRepoVisibilityParamsWithHTTPClient(client *http.Client) *ChangeRepoVisibilityParams {
	var ()
	return &ChangeRepoVisibilityParams{
		HTTPClient: client,
	}
}

/*ChangeRepoVisibilityParams contains all the parameters to send to the API endpoint
for the change repo visibility operation typically these are written to a http.Request
*/
type ChangeRepoVisibilityParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.ChangeVisibility
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change repo visibility params
func (o *ChangeRepoVisibilityParams) WithTimeout(timeout time.Duration) *ChangeRepoVisibilityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change repo visibility params
func (o *ChangeRepoVisibilityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change repo visibility params
func (o *ChangeRepoVisibilityParams) WithContext(ctx context.Context) *ChangeRepoVisibilityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change repo visibility params
func (o *ChangeRepoVisibilityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change repo visibility params
func (o *ChangeRepoVisibilityParams) WithHTTPClient(client *http.Client) *ChangeRepoVisibilityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change repo visibility params
func (o *ChangeRepoVisibilityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the change repo visibility params
func (o *ChangeRepoVisibilityParams) WithBody(body *models.ChangeVisibility) *ChangeRepoVisibilityParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the change repo visibility params
func (o *ChangeRepoVisibilityParams) SetBody(body *models.ChangeVisibility) {
	o.Body = body
}

// WithRepository adds the repository to the change repo visibility params
func (o *ChangeRepoVisibilityParams) WithRepository(repository string) *ChangeRepoVisibilityParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the change repo visibility params
func (o *ChangeRepoVisibilityParams) SetRepository(repository string) {
	o.Repository = repository
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeRepoVisibilityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
