// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/dlespiau/quay-exporter/pkg/models"
)

// ChangeRepoTrustReader is a Reader for the ChangeRepoTrust structure.
type ChangeRepoTrustReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChangeRepoTrustReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewChangeRepoTrustCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewChangeRepoTrustBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewChangeRepoTrustUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewChangeRepoTrustForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewChangeRepoTrustNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewChangeRepoTrustCreated creates a ChangeRepoTrustCreated with default headers values
func NewChangeRepoTrustCreated() *ChangeRepoTrustCreated {
	return &ChangeRepoTrustCreated{}
}

/*ChangeRepoTrustCreated handles this case with default header values.

Successful creation
*/
type ChangeRepoTrustCreated struct {
}

func (o *ChangeRepoTrustCreated) Error() string {
	return fmt.Sprintf("[POST /api/v1/repository/{repository}/changetrust][%d] changeRepoTrustCreated ", 201)
}

func (o *ChangeRepoTrustCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewChangeRepoTrustBadRequest creates a ChangeRepoTrustBadRequest with default headers values
func NewChangeRepoTrustBadRequest() *ChangeRepoTrustBadRequest {
	return &ChangeRepoTrustBadRequest{}
}

/*ChangeRepoTrustBadRequest handles this case with default header values.

Bad Request
*/
type ChangeRepoTrustBadRequest struct {
	Payload *models.APIError
}

func (o *ChangeRepoTrustBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v1/repository/{repository}/changetrust][%d] changeRepoTrustBadRequest  %+v", 400, o.Payload)
}

func (o *ChangeRepoTrustBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewChangeRepoTrustUnauthorized creates a ChangeRepoTrustUnauthorized with default headers values
func NewChangeRepoTrustUnauthorized() *ChangeRepoTrustUnauthorized {
	return &ChangeRepoTrustUnauthorized{}
}

/*ChangeRepoTrustUnauthorized handles this case with default header values.

Session required
*/
type ChangeRepoTrustUnauthorized struct {
	Payload *models.APIError
}

func (o *ChangeRepoTrustUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1/repository/{repository}/changetrust][%d] changeRepoTrustUnauthorized  %+v", 401, o.Payload)
}

func (o *ChangeRepoTrustUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewChangeRepoTrustForbidden creates a ChangeRepoTrustForbidden with default headers values
func NewChangeRepoTrustForbidden() *ChangeRepoTrustForbidden {
	return &ChangeRepoTrustForbidden{}
}

/*ChangeRepoTrustForbidden handles this case with default header values.

Unauthorized access
*/
type ChangeRepoTrustForbidden struct {
	Payload *models.APIError
}

func (o *ChangeRepoTrustForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1/repository/{repository}/changetrust][%d] changeRepoTrustForbidden  %+v", 403, o.Payload)
}

func (o *ChangeRepoTrustForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewChangeRepoTrustNotFound creates a ChangeRepoTrustNotFound with default headers values
func NewChangeRepoTrustNotFound() *ChangeRepoTrustNotFound {
	return &ChangeRepoTrustNotFound{}
}

/*ChangeRepoTrustNotFound handles this case with default header values.

Not found
*/
type ChangeRepoTrustNotFound struct {
	Payload *models.APIError
}

func (o *ChangeRepoTrustNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1/repository/{repository}/changetrust][%d] changeRepoTrustNotFound  %+v", 404, o.Payload)
}

func (o *ChangeRepoTrustNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
