// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteRepositoryParams creates a new DeleteRepositoryParams object
// with the default values initialized.
func NewDeleteRepositoryParams() *DeleteRepositoryParams {
	var ()
	return &DeleteRepositoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRepositoryParamsWithTimeout creates a new DeleteRepositoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteRepositoryParamsWithTimeout(timeout time.Duration) *DeleteRepositoryParams {
	var ()
	return &DeleteRepositoryParams{

		timeout: timeout,
	}
}

// NewDeleteRepositoryParamsWithContext creates a new DeleteRepositoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteRepositoryParamsWithContext(ctx context.Context) *DeleteRepositoryParams {
	var ()
	return &DeleteRepositoryParams{

		Context: ctx,
	}
}

// NewDeleteRepositoryParamsWithHTTPClient creates a new DeleteRepositoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteRepositoryParamsWithHTTPClient(client *http.Client) *DeleteRepositoryParams {
	var ()
	return &DeleteRepositoryParams{
		HTTPClient: client,
	}
}

/*DeleteRepositoryParams contains all the parameters to send to the API endpoint
for the delete repository operation typically these are written to a http.Request
*/
type DeleteRepositoryParams struct {

	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete repository params
func (o *DeleteRepositoryParams) WithTimeout(timeout time.Duration) *DeleteRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete repository params
func (o *DeleteRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete repository params
func (o *DeleteRepositoryParams) WithContext(ctx context.Context) *DeleteRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete repository params
func (o *DeleteRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete repository params
func (o *DeleteRepositoryParams) WithHTTPClient(client *http.Client) *DeleteRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete repository params
func (o *DeleteRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepository adds the repository to the delete repository params
func (o *DeleteRepositoryParams) WithRepository(repository string) *DeleteRepositoryParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the delete repository params
func (o *DeleteRepositoryParams) SetRepository(repository string) {
	o.Repository = repository
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
