// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/dlespiau/quay-exporter/pkg/models"
)

// NewUpdateRepoParams creates a new UpdateRepoParams object
// with the default values initialized.
func NewUpdateRepoParams() *UpdateRepoParams {
	var ()
	return &UpdateRepoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRepoParamsWithTimeout creates a new UpdateRepoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateRepoParamsWithTimeout(timeout time.Duration) *UpdateRepoParams {
	var ()
	return &UpdateRepoParams{

		timeout: timeout,
	}
}

// NewUpdateRepoParamsWithContext creates a new UpdateRepoParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateRepoParamsWithContext(ctx context.Context) *UpdateRepoParams {
	var ()
	return &UpdateRepoParams{

		Context: ctx,
	}
}

// NewUpdateRepoParamsWithHTTPClient creates a new UpdateRepoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateRepoParamsWithHTTPClient(client *http.Client) *UpdateRepoParams {
	var ()
	return &UpdateRepoParams{
		HTTPClient: client,
	}
}

/*UpdateRepoParams contains all the parameters to send to the API endpoint
for the update repo operation typically these are written to a http.Request
*/
type UpdateRepoParams struct {

	/*Body
	  Request body contents.

	*/
	Body *models.RepoUpdate
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update repo params
func (o *UpdateRepoParams) WithTimeout(timeout time.Duration) *UpdateRepoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update repo params
func (o *UpdateRepoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update repo params
func (o *UpdateRepoParams) WithContext(ctx context.Context) *UpdateRepoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update repo params
func (o *UpdateRepoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update repo params
func (o *UpdateRepoParams) WithHTTPClient(client *http.Client) *UpdateRepoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update repo params
func (o *UpdateRepoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update repo params
func (o *UpdateRepoParams) WithBody(body *models.RepoUpdate) *UpdateRepoParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update repo params
func (o *UpdateRepoParams) SetBody(body *models.RepoUpdate) {
	o.Body = body
}

// WithRepository adds the repository to the update repo params
func (o *UpdateRepoParams) WithRepository(repository string) *UpdateRepoParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the update repo params
func (o *UpdateRepoParams) SetRepository(repository string) {
	o.Repository = repository
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRepoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
