// Code generated by go-swagger; DO NOT EDIT.

package signing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new signing API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for signing API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetRepoSignatures Fetches the list of signed tags for the repository.
*/
func (a *Client) GetRepoSignatures(params *GetRepoSignaturesParams, authInfo runtime.ClientAuthInfoWriter) (*GetRepoSignaturesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRepoSignaturesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getRepoSignatures",
		Method:             "GET",
		PathPattern:        "/api/v1/repository/{repository}/signatures",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetRepoSignaturesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetRepoSignaturesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
