// Code generated by go-swagger; DO NOT EDIT.

package robot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteOrgRobotParams creates a new DeleteOrgRobotParams object
// with the default values initialized.
func NewDeleteOrgRobotParams() *DeleteOrgRobotParams {
	var ()
	return &DeleteOrgRobotParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOrgRobotParamsWithTimeout creates a new DeleteOrgRobotParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteOrgRobotParamsWithTimeout(timeout time.Duration) *DeleteOrgRobotParams {
	var ()
	return &DeleteOrgRobotParams{

		timeout: timeout,
	}
}

// NewDeleteOrgRobotParamsWithContext creates a new DeleteOrgRobotParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteOrgRobotParamsWithContext(ctx context.Context) *DeleteOrgRobotParams {
	var ()
	return &DeleteOrgRobotParams{

		Context: ctx,
	}
}

// NewDeleteOrgRobotParamsWithHTTPClient creates a new DeleteOrgRobotParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteOrgRobotParamsWithHTTPClient(client *http.Client) *DeleteOrgRobotParams {
	var ()
	return &DeleteOrgRobotParams{
		HTTPClient: client,
	}
}

/*DeleteOrgRobotParams contains all the parameters to send to the API endpoint
for the delete org robot operation typically these are written to a http.Request
*/
type DeleteOrgRobotParams struct {

	/*Orgname
	  The name of the organization

	*/
	Orgname string
	/*RobotShortname
	  The short name for the robot, without any user or organization prefix

	*/
	RobotShortname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete org robot params
func (o *DeleteOrgRobotParams) WithTimeout(timeout time.Duration) *DeleteOrgRobotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete org robot params
func (o *DeleteOrgRobotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete org robot params
func (o *DeleteOrgRobotParams) WithContext(ctx context.Context) *DeleteOrgRobotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete org robot params
func (o *DeleteOrgRobotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete org robot params
func (o *DeleteOrgRobotParams) WithHTTPClient(client *http.Client) *DeleteOrgRobotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete org robot params
func (o *DeleteOrgRobotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgname adds the orgname to the delete org robot params
func (o *DeleteOrgRobotParams) WithOrgname(orgname string) *DeleteOrgRobotParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the delete org robot params
func (o *DeleteOrgRobotParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WithRobotShortname adds the robotShortname to the delete org robot params
func (o *DeleteOrgRobotParams) WithRobotShortname(robotShortname string) *DeleteOrgRobotParams {
	o.SetRobotShortname(robotShortname)
	return o
}

// SetRobotShortname adds the robotShortname to the delete org robot params
func (o *DeleteOrgRobotParams) SetRobotShortname(robotShortname string) {
	o.RobotShortname = robotShortname
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrgRobotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	// path param robot_shortname
	if err := r.SetPathParam("robot_shortname", o.RobotShortname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
