// Code generated by go-swagger; DO NOT EDIT.

package robot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrgRobotParams creates a new GetOrgRobotParams object
// with the default values initialized.
func NewGetOrgRobotParams() *GetOrgRobotParams {
	var ()
	return &GetOrgRobotParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrgRobotParamsWithTimeout creates a new GetOrgRobotParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrgRobotParamsWithTimeout(timeout time.Duration) *GetOrgRobotParams {
	var ()
	return &GetOrgRobotParams{

		timeout: timeout,
	}
}

// NewGetOrgRobotParamsWithContext creates a new GetOrgRobotParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrgRobotParamsWithContext(ctx context.Context) *GetOrgRobotParams {
	var ()
	return &GetOrgRobotParams{

		Context: ctx,
	}
}

// NewGetOrgRobotParamsWithHTTPClient creates a new GetOrgRobotParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrgRobotParamsWithHTTPClient(client *http.Client) *GetOrgRobotParams {
	var ()
	return &GetOrgRobotParams{
		HTTPClient: client,
	}
}

/*GetOrgRobotParams contains all the parameters to send to the API endpoint
for the get org robot operation typically these are written to a http.Request
*/
type GetOrgRobotParams struct {

	/*Orgname
	  The name of the organization

	*/
	Orgname string
	/*RobotShortname
	  The short name for the robot, without any user or organization prefix

	*/
	RobotShortname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get org robot params
func (o *GetOrgRobotParams) WithTimeout(timeout time.Duration) *GetOrgRobotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get org robot params
func (o *GetOrgRobotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get org robot params
func (o *GetOrgRobotParams) WithContext(ctx context.Context) *GetOrgRobotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get org robot params
func (o *GetOrgRobotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get org robot params
func (o *GetOrgRobotParams) WithHTTPClient(client *http.Client) *GetOrgRobotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get org robot params
func (o *GetOrgRobotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgname adds the orgname to the get org robot params
func (o *GetOrgRobotParams) WithOrgname(orgname string) *GetOrgRobotParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the get org robot params
func (o *GetOrgRobotParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WithRobotShortname adds the robotShortname to the get org robot params
func (o *GetOrgRobotParams) WithRobotShortname(robotShortname string) *GetOrgRobotParams {
	o.SetRobotShortname(robotShortname)
	return o
}

// SetRobotShortname adds the robotShortname to the get org robot params
func (o *GetOrgRobotParams) SetRobotShortname(robotShortname string) {
	o.RobotShortname = robotShortname
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrgRobotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	// path param robot_shortname
	if err := r.SetPathParam("robot_shortname", o.RobotShortname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
