// Code generated by go-swagger; DO NOT EDIT.

package robot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRegenerateOrgRobotTokenParams creates a new RegenerateOrgRobotTokenParams object
// with the default values initialized.
func NewRegenerateOrgRobotTokenParams() *RegenerateOrgRobotTokenParams {
	var ()
	return &RegenerateOrgRobotTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRegenerateOrgRobotTokenParamsWithTimeout creates a new RegenerateOrgRobotTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRegenerateOrgRobotTokenParamsWithTimeout(timeout time.Duration) *RegenerateOrgRobotTokenParams {
	var ()
	return &RegenerateOrgRobotTokenParams{

		timeout: timeout,
	}
}

// NewRegenerateOrgRobotTokenParamsWithContext creates a new RegenerateOrgRobotTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewRegenerateOrgRobotTokenParamsWithContext(ctx context.Context) *RegenerateOrgRobotTokenParams {
	var ()
	return &RegenerateOrgRobotTokenParams{

		Context: ctx,
	}
}

// NewRegenerateOrgRobotTokenParamsWithHTTPClient creates a new RegenerateOrgRobotTokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRegenerateOrgRobotTokenParamsWithHTTPClient(client *http.Client) *RegenerateOrgRobotTokenParams {
	var ()
	return &RegenerateOrgRobotTokenParams{
		HTTPClient: client,
	}
}

/*RegenerateOrgRobotTokenParams contains all the parameters to send to the API endpoint
for the regenerate org robot token operation typically these are written to a http.Request
*/
type RegenerateOrgRobotTokenParams struct {

	/*Orgname
	  The name of the organization

	*/
	Orgname string
	/*RobotShortname
	  The short name for the robot, without any user or organization prefix

	*/
	RobotShortname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the regenerate org robot token params
func (o *RegenerateOrgRobotTokenParams) WithTimeout(timeout time.Duration) *RegenerateOrgRobotTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the regenerate org robot token params
func (o *RegenerateOrgRobotTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the regenerate org robot token params
func (o *RegenerateOrgRobotTokenParams) WithContext(ctx context.Context) *RegenerateOrgRobotTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the regenerate org robot token params
func (o *RegenerateOrgRobotTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the regenerate org robot token params
func (o *RegenerateOrgRobotTokenParams) WithHTTPClient(client *http.Client) *RegenerateOrgRobotTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the regenerate org robot token params
func (o *RegenerateOrgRobotTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrgname adds the orgname to the regenerate org robot token params
func (o *RegenerateOrgRobotTokenParams) WithOrgname(orgname string) *RegenerateOrgRobotTokenParams {
	o.SetOrgname(orgname)
	return o
}

// SetOrgname adds the orgname to the regenerate org robot token params
func (o *RegenerateOrgRobotTokenParams) SetOrgname(orgname string) {
	o.Orgname = orgname
}

// WithRobotShortname adds the robotShortname to the regenerate org robot token params
func (o *RegenerateOrgRobotTokenParams) WithRobotShortname(robotShortname string) *RegenerateOrgRobotTokenParams {
	o.SetRobotShortname(robotShortname)
	return o
}

// SetRobotShortname adds the robotShortname to the regenerate org robot token params
func (o *RegenerateOrgRobotTokenParams) SetRobotShortname(robotShortname string) {
	o.RobotShortname = robotShortname
}

// WriteToRequest writes these params to a swagger request
func (o *RegenerateOrgRobotTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orgname
	if err := r.SetPathParam("orgname", o.Orgname); err != nil {
		return err
	}

	// path param robot_shortname
	if err := r.SetPathParam("robot_shortname", o.RobotShortname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
