// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAggregateRepoLogsParams creates a new GetAggregateRepoLogsParams object
// with the default values initialized.
func NewGetAggregateRepoLogsParams() *GetAggregateRepoLogsParams {
	var ()
	return &GetAggregateRepoLogsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAggregateRepoLogsParamsWithTimeout creates a new GetAggregateRepoLogsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAggregateRepoLogsParamsWithTimeout(timeout time.Duration) *GetAggregateRepoLogsParams {
	var ()
	return &GetAggregateRepoLogsParams{

		timeout: timeout,
	}
}

// NewGetAggregateRepoLogsParamsWithContext creates a new GetAggregateRepoLogsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAggregateRepoLogsParamsWithContext(ctx context.Context) *GetAggregateRepoLogsParams {
	var ()
	return &GetAggregateRepoLogsParams{

		Context: ctx,
	}
}

// NewGetAggregateRepoLogsParamsWithHTTPClient creates a new GetAggregateRepoLogsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAggregateRepoLogsParamsWithHTTPClient(client *http.Client) *GetAggregateRepoLogsParams {
	var ()
	return &GetAggregateRepoLogsParams{
		HTTPClient: client,
	}
}

/*GetAggregateRepoLogsParams contains all the parameters to send to the API endpoint
for the get aggregate repo logs operation typically these are written to a http.Request
*/
type GetAggregateRepoLogsParams struct {

	/*Endtime
	  Latest time to which to get logs (%m/%d/%Y %Z)

	*/
	Endtime *string
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*Starttime
	  Earliest time from which to get logs (%m/%d/%Y %Z)

	*/
	Starttime *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) WithTimeout(timeout time.Duration) *GetAggregateRepoLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) WithContext(ctx context.Context) *GetAggregateRepoLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) WithHTTPClient(client *http.Client) *GetAggregateRepoLogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEndtime adds the endtime to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) WithEndtime(endtime *string) *GetAggregateRepoLogsParams {
	o.SetEndtime(endtime)
	return o
}

// SetEndtime adds the endtime to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) SetEndtime(endtime *string) {
	o.Endtime = endtime
}

// WithRepository adds the repository to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) WithRepository(repository string) *GetAggregateRepoLogsParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) SetRepository(repository string) {
	o.Repository = repository
}

// WithStarttime adds the starttime to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) WithStarttime(starttime *string) *GetAggregateRepoLogsParams {
	o.SetStarttime(starttime)
	return o
}

// SetStarttime adds the starttime to the get aggregate repo logs params
func (o *GetAggregateRepoLogsParams) SetStarttime(starttime *string) {
	o.Starttime = starttime
}

// WriteToRequest writes these params to a swagger request
func (o *GetAggregateRepoLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Endtime != nil {

		// query param endtime
		var qrEndtime string
		if o.Endtime != nil {
			qrEndtime = *o.Endtime
		}
		qEndtime := qrEndtime
		if qEndtime != "" {
			if err := r.SetQueryParam("endtime", qEndtime); err != nil {
				return err
			}
		}

	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if o.Starttime != nil {

		// query param starttime
		var qrStarttime string
		if o.Starttime != nil {
			qrStarttime = *o.Starttime
		}
		qStarttime := qrStarttime
		if qStarttime != "" {
			if err := r.SetQueryParam("starttime", qStarttime); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
