// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAggregateUserLogsParams creates a new GetAggregateUserLogsParams object
// with the default values initialized.
func NewGetAggregateUserLogsParams() *GetAggregateUserLogsParams {
	var ()
	return &GetAggregateUserLogsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAggregateUserLogsParamsWithTimeout creates a new GetAggregateUserLogsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAggregateUserLogsParamsWithTimeout(timeout time.Duration) *GetAggregateUserLogsParams {
	var ()
	return &GetAggregateUserLogsParams{

		timeout: timeout,
	}
}

// NewGetAggregateUserLogsParamsWithContext creates a new GetAggregateUserLogsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAggregateUserLogsParamsWithContext(ctx context.Context) *GetAggregateUserLogsParams {
	var ()
	return &GetAggregateUserLogsParams{

		Context: ctx,
	}
}

// NewGetAggregateUserLogsParamsWithHTTPClient creates a new GetAggregateUserLogsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAggregateUserLogsParamsWithHTTPClient(client *http.Client) *GetAggregateUserLogsParams {
	var ()
	return &GetAggregateUserLogsParams{
		HTTPClient: client,
	}
}

/*GetAggregateUserLogsParams contains all the parameters to send to the API endpoint
for the get aggregate user logs operation typically these are written to a http.Request
*/
type GetAggregateUserLogsParams struct {

	/*Endtime
	  Latest time to which to get logs. (%m/%d/%Y %Z)

	*/
	Endtime *string
	/*Performer
	  Username for which to filter logs.

	*/
	Performer *string
	/*Starttime
	  Earliest time from which to get logs. (%m/%d/%Y %Z)

	*/
	Starttime *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) WithTimeout(timeout time.Duration) *GetAggregateUserLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) WithContext(ctx context.Context) *GetAggregateUserLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) WithHTTPClient(client *http.Client) *GetAggregateUserLogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEndtime adds the endtime to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) WithEndtime(endtime *string) *GetAggregateUserLogsParams {
	o.SetEndtime(endtime)
	return o
}

// SetEndtime adds the endtime to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) SetEndtime(endtime *string) {
	o.Endtime = endtime
}

// WithPerformer adds the performer to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) WithPerformer(performer *string) *GetAggregateUserLogsParams {
	o.SetPerformer(performer)
	return o
}

// SetPerformer adds the performer to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) SetPerformer(performer *string) {
	o.Performer = performer
}

// WithStarttime adds the starttime to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) WithStarttime(starttime *string) *GetAggregateUserLogsParams {
	o.SetStarttime(starttime)
	return o
}

// SetStarttime adds the starttime to the get aggregate user logs params
func (o *GetAggregateUserLogsParams) SetStarttime(starttime *string) {
	o.Starttime = starttime
}

// WriteToRequest writes these params to a swagger request
func (o *GetAggregateUserLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Endtime != nil {

		// query param endtime
		var qrEndtime string
		if o.Endtime != nil {
			qrEndtime = *o.Endtime
		}
		qEndtime := qrEndtime
		if qEndtime != "" {
			if err := r.SetQueryParam("endtime", qEndtime); err != nil {
				return err
			}
		}

	}

	if o.Performer != nil {

		// query param performer
		var qrPerformer string
		if o.Performer != nil {
			qrPerformer = *o.Performer
		}
		qPerformer := qrPerformer
		if qPerformer != "" {
			if err := r.SetQueryParam("performer", qPerformer); err != nil {
				return err
			}
		}

	}

	if o.Starttime != nil {

		// query param starttime
		var qrStarttime string
		if o.Starttime != nil {
			qrStarttime = *o.Starttime
		}
		qStarttime := qrStarttime
		if qStarttime != "" {
			if err := r.SetQueryParam("starttime", qStarttime); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
