// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListRepoLogsParams creates a new ListRepoLogsParams object
// with the default values initialized.
func NewListRepoLogsParams() *ListRepoLogsParams {
	var ()
	return &ListRepoLogsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListRepoLogsParamsWithTimeout creates a new ListRepoLogsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListRepoLogsParamsWithTimeout(timeout time.Duration) *ListRepoLogsParams {
	var ()
	return &ListRepoLogsParams{

		timeout: timeout,
	}
}

// NewListRepoLogsParamsWithContext creates a new ListRepoLogsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListRepoLogsParamsWithContext(ctx context.Context) *ListRepoLogsParams {
	var ()
	return &ListRepoLogsParams{

		Context: ctx,
	}
}

// NewListRepoLogsParamsWithHTTPClient creates a new ListRepoLogsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListRepoLogsParamsWithHTTPClient(client *http.Client) *ListRepoLogsParams {
	var ()
	return &ListRepoLogsParams{
		HTTPClient: client,
	}
}

/*ListRepoLogsParams contains all the parameters to send to the API endpoint
for the list repo logs operation typically these are written to a http.Request
*/
type ListRepoLogsParams struct {

	/*Endtime
	  Latest time to which to get logs (%m/%d/%Y %Z)

	*/
	Endtime *string
	/*NextPage
	  The page token for the next page

	*/
	NextPage *string
	/*Page
	  The page number for the logs

	*/
	Page *int64
	/*Repository
	  The full path of the repository. e.g. namespace/name

	*/
	Repository string
	/*Starttime
	  Earliest time from which to get logs (%m/%d/%Y %Z)

	*/
	Starttime *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list repo logs params
func (o *ListRepoLogsParams) WithTimeout(timeout time.Duration) *ListRepoLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list repo logs params
func (o *ListRepoLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list repo logs params
func (o *ListRepoLogsParams) WithContext(ctx context.Context) *ListRepoLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list repo logs params
func (o *ListRepoLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list repo logs params
func (o *ListRepoLogsParams) WithHTTPClient(client *http.Client) *ListRepoLogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list repo logs params
func (o *ListRepoLogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEndtime adds the endtime to the list repo logs params
func (o *ListRepoLogsParams) WithEndtime(endtime *string) *ListRepoLogsParams {
	o.SetEndtime(endtime)
	return o
}

// SetEndtime adds the endtime to the list repo logs params
func (o *ListRepoLogsParams) SetEndtime(endtime *string) {
	o.Endtime = endtime
}

// WithNextPage adds the nextPage to the list repo logs params
func (o *ListRepoLogsParams) WithNextPage(nextPage *string) *ListRepoLogsParams {
	o.SetNextPage(nextPage)
	return o
}

// SetNextPage adds the nextPage to the list repo logs params
func (o *ListRepoLogsParams) SetNextPage(nextPage *string) {
	o.NextPage = nextPage
}

// WithPage adds the page to the list repo logs params
func (o *ListRepoLogsParams) WithPage(page *int64) *ListRepoLogsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the list repo logs params
func (o *ListRepoLogsParams) SetPage(page *int64) {
	o.Page = page
}

// WithRepository adds the repository to the list repo logs params
func (o *ListRepoLogsParams) WithRepository(repository string) *ListRepoLogsParams {
	o.SetRepository(repository)
	return o
}

// SetRepository adds the repository to the list repo logs params
func (o *ListRepoLogsParams) SetRepository(repository string) {
	o.Repository = repository
}

// WithStarttime adds the starttime to the list repo logs params
func (o *ListRepoLogsParams) WithStarttime(starttime *string) *ListRepoLogsParams {
	o.SetStarttime(starttime)
	return o
}

// SetStarttime adds the starttime to the list repo logs params
func (o *ListRepoLogsParams) SetStarttime(starttime *string) {
	o.Starttime = starttime
}

// WriteToRequest writes these params to a swagger request
func (o *ListRepoLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Endtime != nil {

		// query param endtime
		var qrEndtime string
		if o.Endtime != nil {
			qrEndtime = *o.Endtime
		}
		qEndtime := qrEndtime
		if qEndtime != "" {
			if err := r.SetQueryParam("endtime", qEndtime); err != nil {
				return err
			}
		}

	}

	if o.NextPage != nil {

		// query param next_page
		var qrNextPage string
		if o.NextPage != nil {
			qrNextPage = *o.NextPage
		}
		qNextPage := qrNextPage
		if qNextPage != "" {
			if err := r.SetQueryParam("next_page", qNextPage); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if o.Starttime != nil {

		// query param starttime
		var qrStarttime string
		if o.Starttime != nil {
			qrStarttime = *o.Starttime
		}
		qStarttime := qrStarttime
		if qStarttime != "" {
			if err := r.SetQueryParam("starttime", qStarttime); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
